(function(g){var window=this;'use strict';var $3=function(a){a.ma("cardstatechange",a.pk()&&a.po()?1:0)},a4=function(a,b){var c=g.Ia(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},gcb=function(a){var b=g.Rl(a);
a=g.$l(a);return new g.Gl(b.x,b.y,a.width,a.height)},hcb=function(a){return Math.pow(a,3)},icb=function(a){return 3*a*a-2*a*a*a},d4=function(a){a=g.Oa(a);
delete b4[a];g.Rc(b4)&&c4&&c4.stop()},kcb=function(){c4||(c4=new g.qo(function(){jcb()},20));
var a=c4;a.isActive()||a.start()},jcb=function(){var a=g.Ra();
g.Fc(b4,function(b){lcb(b,a)});
g.Rc(b4)||kcb()},e4=function(a,b,c,d){g.Ko.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.u=a;this.T=b;this.duration=c;this.I=d;this.coords=[];this.progress=this.J=0;this.D=null},lcb=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.J=1E3/(b-a.D);a.D=b;mcb(a,a.progress);1==a.progress?(a.j=0,d4(a),a.onFinish(),a.Bq()):a.fd()&&a.OI()},mcb=function(a,b){"function"===typeof a.I&&(b=a.I(b));
a.coords=Array(a.u.length);for(var c=0;c<a.u.length;c++)a.coords[c]=(a.T[c]-a.u[c])*b+a.u[c]},ncb=function(a,b){g.eb.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.J;this.state=b.j},f4=function(a,b,c,d,e){e4.call(this,b,c,d,e);
this.element=a},ocb=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
f4.call(this,a,b,c,d,e)},pcb=function(a){g.C.call(this);
this.u=a||window;this.j=[]},g4=function(a){return a.baseUrl||null},h4=function(a,b){return g.Km(g.vh(a,b),function(c){return!!c})},qcb=function(a,b,c){function d(R){var Y=R.hovercardButton;
if(!Y)return null;Y=Y.subscribeButtonRenderer;if(!Y)return null;var P=f(Y.unsubscribedButtonText),pa=f(Y.subscribedButtonText);if(Y.subscribed){var la=f(Y.subscriberCountWithUnsubscribeText);var Ka=f(Y.subscriberCountText)}else la=f(Y.subscriberCountText),Ka=f(Y.subscriberCountWithSubscribeText);var cb=null;if(R.signinEndpoint){cb=a4(R,"signinEndpoint","webNavigationEndpointData","url");if(!cb){var Na,Ua;cb=null==(Ua=g.K(null==(Na=Y.signInEndpoint)?void 0:Na.commandMetadata,g.V2))?void 0:Ua.url}if(!cb)return null}return P&&
(pa||cb)?{subscribed:Y.subscribed,subscribeText:P,subscribeCount:la,unsubscribeText:pa,unsubscribeCount:Ka,enabled:Y.enabled,signinUrl:cb,classic:R.useClassicSubscribeButton}:null}
function e(R){if(R){var Y=[],P=R.videoId;P&&Y.push("v="+P);(P=R.playlistId)&&Y.push("list="+P);(R=R.startTimeSeconds)&&Y.push("t="+R);return"/watch?"+Y.join("&")}}
function f(R){if(!R)return null;var Y=R.simpleText;return Y?Y:R.runs?g.vh(R.runs,function(P){return P.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=!1,q=null,r=null,w=null,x=null,z=!1,B=null,E=null,G=null,F=null,L=null,O=null;if("VIDEO"===h)g.K(l,g.xK)?m=g.K(l,g.xK).url:(O=g.K(l,g.wK),m=e(O)),n=!1,q=a,b.thumbnailOverlays?(p=b.thumbnailOverlays[0].thumbnailOverlayTimeStatusRenderer,r=f(p.text),p="LIVE"===p.style):r=f(b.videoDuration);else if("PLAYLIST"===h)g.K(l,g.xK)?m=g.K(l,g.xK).url:(O=g.K(l,g.wK),m=e(O)),n=!1,q=a,w=f(b.playlistLength);else if("CHANNEL"===
h){if(z=a4(l,"browseEndpoint","browseId"))x=z,m="/channel/"+x;n=!1;q="new";(z=!!b.isSubscribe)?B=d(b):E=f(b.subscribersText)}else"WEBSITE"===h?((G=a4(l,"urlEndpoint","url"))&&(m=G),n=!0,q="new",G=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(F=f(b.productPrice)),b.additionalFeesText&&(L=f(b.additionalFeesText)),(n=a4(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=a4(b,"title","accessibility","accessibilityData","label");var U=b.endpoint?b.endpoint.clickTrackingParams:null,
ba="";if(b.metadata){var V=f(b.metadata);V&&(ba=V)}return{id:"element-"+c,type:h,title:f(b.title),metadata:ba,callToAction:f(b.callToAction),MS:b.image,iconUrl:G,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,kC:p,playlistLength:w,channelId:x,subscribeButton:B,subscribersText:E,isSubscribe:z,Et:m||null,j4:n,sessionData:U?{itct:U}:null,j9:q,KA:a?a:null,isPlaceholder:b.isPlaceholder,
impressionUrls:h4(b.impressionUrls||[],g4),X3:h4(b.hovercardShowUrls||[],g4),clickUrls:h4(l.loggingUrls||[],g4),visualElement:g.PC(b.trackingParams),productPrice:F,additionalFeesText:L,watchEndpoint:O||null}},rcb=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:h4(a.impressionUrls||[],g4),elements:h4(a.elements||[],function(d,e){return qcb(b,d,e)})};
a.trackingParams&&(c.visualElement=g.PC(a.trackingParams));return c},scb=function(a){g.hS.call(this,a);
this.B=this.endscreen=null;this.j={};this.D={};this.C=this.u=null;this.J=[];this.Y=!0;this.I=0;a=a.V();this.T=g.uI(a)||"profilepage"===a.Fa;this.ea=a.experiments.qb("web_rounded_thumbnails");this.events=new g.nG(this);g.D(this,this.events);this.events.S(this.player,g.mC("creatorendscreen"),this.onCueRangeEnter);this.events.S(this.player,g.nC("creatorendscreen"),this.onCueRangeExit);this.events.S(this.player,"resize",this.Eb);this.events.S(window,"focus",this.T7);this.load();var b=g.Ne("STYLE");(g.Be("HEAD")[0]||
document.body).appendChild(b);g.ab(this,function(){g.Xe(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},tcb=function(a){return a.player.getVideoData().D?"current":a.T?"new":"current"},i4=function(a){return"creator-endscreen-editor"===a.player.V().playerStyle},ucb=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.B&&a.B.abort();c={method:"POST",onFinish:function(e){var f=a.B=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=rcb(f,tcb(a))));j4(a,f)},
urlParams:{v:c},withCredentials:!0};a.T&&(c.urlParams.ptype="embedded");var d=b.Xw;d&&(c.postParams={ad_tracking:d});if(b=g.hCa(b))if(b=g.Ud(b),b=g.Sd(b))a.B=g.Vw(b,c)},j4=function(a,b,c){c=void 0===c?!0:c;
a.player.Gf("creatorendscreen");a.u&&(a.u.dispose(),a.u=null,a.C.dispose(),a.C=null);for(var d=g.t(Object.values(a.j)),e=d.next();!e.done;e=d.next())e.value.dispose();a.j={};a.D={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.I=0;if((a.endscreen=b)&&b.elements){c&&vcb(a);c=[];d=new g.kC(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.V().u||(a.u=new g.T({G:"div",N:"ytp-ce-shadow"}),g.oR(a.player,a.u.element,4),a.C=new g.QO(a.u,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=wcb(a,e);if(f){a.j[e.id]=f;a.D[e.id]=e;g.oR(a.player,f.element,4);var h=new g.kC(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);xcb(a,f,e)}else g.QB(new g.Sx("buildEndscreenElement null",
e))}a.player.Be(c);a.Eb()}},vcb=function(a){var b=g.SC(),c=g.TC();
c&&b&&a.endscreen.visualElement&&g.Bw(g.aN)(void 0,c,b,a.endscreen.visualElement)},wcb=function(a,b){var c=null;
switch(b.type){case "VIDEO":a={G:"div",Ia:["ytp-ce-element","ytp-ce-video"],X:{tabindex:"0","aria-label":b.KA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-covering-image",X:k4(b)},{G:"div",N:"ytp-ce-covering-shadow-top"},{G:"a",N:"ytp-ce-covering-overlay",X:{href:l4(a,b.Et),tabindex:"-1"},W:[{G:"div",Ia:["ytp-ce-video-title","ytp-webkit-ellipsis"],X:{dir:g.Oo(b.title||"")},qa:b.title},{G:"div",N:b.kC?"ytp-ce-live-video-duration":"ytp-ce-video-duration",qa:b.videoDuration||
void 0}]}]};c=new g.T(a);break;case "PLAYLIST":a={G:"div",Ia:["ytp-ce-element","ytp-ce-playlist"],X:{tabindex:"0","aria-label":b.KA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-covering-image",X:k4(b)},{G:"div",N:"ytp-ce-covering-shadow-top"},{G:"a",N:"ytp-ce-covering-overlay",X:{href:l4(a,b.Et),tabindex:"-1"},W:[{G:"div",Ia:["ytp-ce-playlist-title","ytp-webkit-ellipsis"],X:{dir:g.Oo(b.title||"")},qa:b.title},{G:"div",N:"ytp-ce-playlist-count",W:[{G:"div",N:"ytp-ce-playlist-icon"},
{G:"div",N:"ytp-ce-playlist-count-text",qa:b.playlistLength||void 0}]}]}]};c=new g.T(a);break;case "CHANNEL":c={G:"div",Ia:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],X:{tabindex:"0","aria-label":b.KA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",W:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",W:[{G:"div",
N:"ytp-ce-expanding-overlay-body",W:[{G:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{G:"a",Ia:["ytp-ce-channel-title","ytp-ce-link"],X:{href:l4(a,b.Et),target:"_blank",tabindex:"-1",dir:g.Oo(b.title||"")},qa:b.title},b.subscribeButton?{G:"div",N:"ytp-ce-subscribe-container",W:[{G:"div",N:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{G:"div",N:"ytp-ce-channel-subscribers-text",qa:b.subscribersText}:"",b.metadata?{G:"div",Ia:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
qa:b.metadata}:""]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",X:k4(b)}]};c=new g.T(c);var d=g.Ce(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.yo(d,"ytp-ce-subscribe-button");if(a.player.V().u){var e=null;var f=b.sessionData.itct}else e="endscreen",f=null;e=new g.lT(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,
b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={G:"div",Ia:["ytp-ce-element","ytp-ce-website"],X:{tabindex:"0","aria-label":b.KA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",W:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",W:[{G:"div",N:"ytp-ce-expanding-overlay-body",
W:[{G:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{G:"div",N:"ytp-ce-website-title",X:{dir:g.Oo(b.title||"")},qa:b.title},{G:"div",N:"ytp-ce-website-metadata",qa:b.metadata},{G:"a",Ia:["ytp-ce-website-goto","ytp-ce-link"],X:{href:l4(a,b.Et),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",X:k4(b)},{G:"div",N:"ytp-ce-expanding-icon",X:ycb(b.iconUrl)}]};c=new g.T(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={G:"div",N:"ytp-ce-merchandise-price-container",
W:[{G:"div",N:"ytp-ce-merchandise-price",qa:b.productPrice}]},b.additionalFeesText&&c.W.push({G:"div",N:"ytp-ce-merchandise-additional-fees",qa:b.additionalFeesText})),a={G:"div",Ia:["ytp-ce-element","ytp-ce-merchandise"],X:{tabindex:"0","aria-label":b.KA||"","aria-hidden":"true"},W:[{G:"div",N:"ytp-ce-element-shadow"},{G:"div",N:"ytp-ce-expanding-overlay",W:[{G:"div",N:"ytp-ce-expanding-overlay-hider"},{G:"div",N:"ytp-ce-expanding-overlay-background"},{G:"div",N:"ytp-ce-expanding-overlay-content",
W:[{G:"div",N:"ytp-ce-expanding-overlay-body",W:[{G:"div",N:"ytp-ce-expanding-overlay-body-padding",W:[{G:"div",N:"ytp-ce-merchandise-title",X:{dir:g.Oo(b.title||"")},qa:b.title},c,{G:"div",N:"ytp-ce-merchandise-metadata",qa:b.metadata},{G:"a",Ia:["ytp-ce-merchandise-goto","ytp-ce-link"],X:{href:l4(a,b.Et),target:"_blank",tabindex:"-1"},qa:b.callToAction}]}]}]}]},{G:"div",N:"ytp-ce-expanding-image",X:k4(b)},{G:"div",N:"ytp-ce-merchandise-invideo-cta-container",W:[{G:"div",N:"ytp-ce-merchandise-invideo-cta",
qa:b.callToAction||void 0}]}]},c=new g.T(a)}b.isPlaceholder&&g.yo(c.element,"ytp-ce-placeholder");return c},k4=function(a){if(a.MS)var b=a.MS.thumbnails;
return ycb(b?b[b.length-1].url:null)},ycb=function(a){return a?{style:"background-image: url("+a+")"}:{}},xcb=function(a,b,c){function d(m){m&&(b.Qa("blur",function(){"none"!=m.style.display&&a.Y&&m.focus()}),b.S(m,"focus",f),b.S(m,"blur",h))}
function e(m){a.I+=m;0<a.I?(g.yo(b.element,"ytp-ce-force-expand"),m4(a,c.id,!0)):(g.Ao(b.element,"ytp-ce-force-expand"),g.Ao(b.element,"ytp-ce-element-hover"),m4(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Qa("mouseenter",function(){zcb(a,b,c)});
b.Qa("mouseleave",function(){Acb(a,b,c)});
a.player.V().u||b.Qa("click",function(){g.yo(b.element,"ytp-ce-element-hover")});
b.Qa("click",function(m){Bcb(a,c,m)});
b.Qa("keypress",function(m){Bcb(a,c,m)});
b.Qa("focus",function(){zcb(a,b,c)});
b.Qa("blur",function(){Acb(a,b,c)});
b.Qa("touchstart",function(){zcb(a,b,c)});
var l=g.He("ytp-ce-expanding-overlay-hider",b.element);l&&b.S(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.Ao(b.element,"ytp-ce-element-hover");g.Ao(b.element,"ytp-ce-force-expand")});
b.Qa("keydown",function(m){a.Y=9===m.keyCode&&!m.shiftKey});
d(g.He("ytp-sb-subscribe",b.element));d(g.He("ytp-sb-unsubscribe",b.element));b.Qa("focus",f);b.Qa("blur",h)},Bcb=function(a,b,c){if(b.Et&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.xo(d,"ytp-ce-element");){g.xo(d,"subscribe-label")&&Ccb(a,b);
if(g.xo(d,"ytp-ce-channel-subscribe"))return;d=g.Ye(d)}if(!d||g.xo(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.j[b.id])Acb(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.j9)Ccb(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Ud(l4(a,b.Et)),g.PL(g.Sd(c),void 0,b.sessionData);else{var e=g.MI(a.player.V())||a.player.getVideoData().D,f=function(){var h=l4(a,b.Et),l=b.sessionData,m=b.watchEndpoint,n=g.Hw(h);e&&n&&(n.v||n.list)?a.player.Hn(n.v,
l,n.list,!1,void 0,m||void 0):g.NL(h,l)};
Ccb(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},l4=function(a,b){a=a.player.V();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.VI(a)+b}else return"";return b},zcb=function(a,b,c){g.xo(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.yo(b.element,"ytp-ce-element-hover"):a.player.V().u?(new g.qo(function(){g.yo(b.element,"ytp-ce-element-hover")},200)).start():g.yo(b.element,"ytp-ce-element-hover"),n4(a,c.X3),m4(a,c.id,!0))},Acb=function(a,b,c){g.Ao(b.element,"ytp-ce-element-hover");
g.Ao(b.element,"ytp-ce-force-expand");m4(a,c.id,!1)},m4=function(a,b,c){a.u&&(c?a.C.show():a.C.hide());
for(var d=g.t(Object.keys(a.j)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.Co(a.j[e].element,"ytp-ce-element-shadow-show",c)},n4=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||i4(a))c&&c();else{b=Dcb(a,b);var e=0,f=!1,h=new g.qo(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Jz(b[a],d)}},Ccb=function(a,b,c){n4(a,b.clickUrls,c);
(a=g.TC())&&b.j4&&g.hN(a,b.visualElement)},Dcb=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(Ecb(b[d],c));return a},Ecb=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},Fcb=function(a){return"string"===typeof a?a:""},o4=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},Gcb=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.j=d},p4=function(a){return a.value?a.value:null},q4=function(a){if(!a)return null;
var b=g.Ud(Fcb(a.value));b=g.Sd(b);if(!b)return null;var c=o4(a.target,Hcb,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new Gcb(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},Icb=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Lcb=function(a){if(!a)return null;
var b=o4(a.type,Jcb),c=o4(a.trigger,Kcb);a=a.url;a=Array.isArray(a)&&a.length?a[0]:a;a=q4(a?a:null);return b?new Icb(b,c,a):null},Mcb=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},Ncb=function(a,b){return g.jb(a.action,b)},Ocb=function(a,b){this.context=a;
this.j=b},Pcb=function(a){return a.customMessage?r4("div","iv-card-message",a.customMessage):""},s4=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{G:"div",N:"iv-card-image",X:{style:a},W:c}},Qcb=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.t(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(r4("li","",c.value));return{G:"ul",N:"iv-card-meta-info",W:b}},r4=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.Oo(c);return{G:a,X:b,qa:c}},Rcb=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.TA&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.TA+");");c.dir=g.Oo(a.customMessage);var d=[{G:"span",qa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({G:"span",N:"iv-card-link-icon"}));return{G:"div",Ia:b,X:c,W:d}},t4=function(a,b,c,d){if(d){b=g.t(b);
for(var e=b.next();!e.done;e=b.next())a.j(e.value,d,c.id,c.sessionData,c.Qi.click,5)}},Scb=function(a,b){this.merchant=a;
this.price=b},Tcb=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,"").split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},Ucb=function(a,b){return b?b:Tcb(a)?"current":"new"},u4=function(a,b){g.C.call(this);
var c=this;this.element=a;this.context=b;this.tb=!1;this.Za=new Map;this.fb=new Map;this.context.F.addEventListener(g.mC("annotations_module"),function(d){(d=c.Za.get(d))&&d.apply(c)});
this.context.F.addEventListener(g.nC("annotations_module"),function(d){(d=c.fb.get(d))&&d.apply(c)})},v4=function(a,b,c,d,e,f,h){a.context.j.Qa(b,"click",function(l){a.QI(c,d,e,f||[],h||0,l)});
a.context.j.Qa(b,"touchstart",function(){a.tb=!1});
a.context.j.Qa(b,"touchmove",function(){a.tb=!0})},Vcb=function(a){var b;
return(null==(b=g.K(a,g.xK))?0:b.url)?g.K(a,g.xK).url:(a=g.K(a,g.wK))&&a.videoId?(b="/watch?v="+a.videoId,a.playlistId&&(b+="&list="+a.playlistId),a.index&&(b+="&index="+a.index),a.startTimeSeconds&&(b+="&t="+a.startTimeSeconds),b):null},w4=function(a,b,c){return{kU:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
FX:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
YH:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},Wcb=function(a,b,c){u4.call(this,b,c);
var d=this;this.F=a;this.eventId=null;this.Ma=this.pc=this.B=this.isInitialized=!1;this.cards=[];this.Fb=this.T=this.Ja=this.D=this.Ta=this.j=null;this.ea=[];this.oa=this.J=this.Vf=this.Fa=null;this.I=0;this.ya=new g.qo(function(){},c.Z.dh?4E3:3E3);
g.D(this,this.ya);this.kb=new g.qo(function(){});
g.D(this,this.kb);this.Aa=new Ocb(c,function(e,f,h,l,m,n){v4(d,e,f,h,l,m,n)});
this.Y=new g.T({G:"div",N:"iv-drawer",X:{id:"iv-drawer"},W:[{G:"div",N:"iv-drawer-header",X:{"aria-role":"heading"},W:[{G:"span",N:"iv-drawer-header-text"},{G:"button",Ia:["iv-drawer-close-button","ytp-button"],X:{"aria-label":"\u0421\u043a\u0440\u044b\u0442\u044c \u043f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0438",tabindex:"0"}}]},{G:"div",N:"iv-drawer-content"}]});g.D(this,this.Y);this.C=this.Y.element;this.jb=new g.QO(this.Y,330);g.D(this,this.jb);this.Tb=g.He("iv-drawer-header-text",this.C);
this.u=g.He("iv-drawer-content",this.C);this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.pc&&x4(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.pc=d.B)&&y4(d)});
this.Ra=new g.nG(this);g.D(this,this.Ra);this.F.addEventListener("videodatachange",this.Cs.bind(this))},Xcb=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){x4(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){y4(a)});
var c=b.headerText;g.$e(a.Tb,c);a.T&&a.T.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.Fa=g.PC(b.trackingParams);a.J=g.PC(b.closeTrackingParams);a.Vf=g.PC(b.iconTrackingParams)},Ycb=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.I,d=a.F.V().experiments.qb("enable_error_corrections_infocard_web_client");
if(!b.content&&b.teaser.simpleCardTeaserRenderer&&d){var e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.uC(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:{},sponsored:!1,Qi:{},qo:null,Xk:e.trackingParams?g.PC(e.trackingParams):null,Vf:f&&f.trackingParams?g.PC(f.trackingParams):null,imageUrl:"",displayDomain:null,showLinkIcon:!1,
TA:null,title:"",customMessage:"",url:null,onClickCommand:e.onTapCommand||null};z4(a,b)}else{var h;if(null==(h=b.content)?0:h.simpleCardContentRenderer){if(!b.cueRanges.length)return;f=null==(e=b.content)?void 0:e.simpleCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;var l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"simple",teaserText:g.uC(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,
sessionData:A4(a,c,b,f),sponsored:!1,Qi:w4(f,e,f.command),qo:f.trackingParams?g.PC(f.trackingParams):null,Xk:e.trackingParams?g.PC(e.trackingParams):null,Vf:l&&l.trackingParams?g.PC(l.trackingParams):null,imageUrl:B4(f.image.thumbnails,290).url,displayDomain:f.displayDomain?g.uC(f.displayDomain):null,showLinkIcon:!!f.showLinkIcon,TA:null,title:f.title?g.uC(f.title):"",customMessage:f.callToAction?g.uC(f.callToAction):"",url:g.K(f.command,g.xK).url?q4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.K(f.command,g.xK).url}):null,onClickCommand:null};z4(a,b)}else{var m;if(null==(m=b.content)?0:m.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(f=b.content)?void 0:f.collaboratorInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"collaborator",teaserText:g.uC(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),
autoOpen:!!b.autoOpen,sessionData:A4(a,c,b,e),sponsored:!1,Qi:w4(e,f,e.endpoint),qo:e.trackingParams?g.PC(e.trackingParams):null,Xk:f.trackingParams?g.PC(f.trackingParams):null,Vf:l&&l.trackingParams?g.PC(l.trackingParams):null,channelId:g.K(e.endpoint,C4).browseId,customMessage:e.customText?g.uC(e.customText):null,zW:B4(e.channelAvatar.thumbnails,290).url,title:e.channelName?g.uC(e.channelName):"",metaInfo:[e.subscriberCountText?g.uC(e.subscriberCountText):""],url:q4({pause_on_navigation:!a.context.videoData.isLivePlayback,
target:"new",value:g.K(e.endpoint,C4).canonicalBaseUrl?g.K(e.endpoint,C4).canonicalBaseUrl:"/channel/"+g.K(e.endpoint,C4).browseId}),onClickCommand:null};z4(a,b)}else{var n;if(null==(n=b.content)?0:n.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;e=null==(l=b.content)?void 0:l.playlistInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"playlist",teaserText:g.uC(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:A4(a,c,b,e),sponsored:!1,Qi:w4(e,f,e.action),qo:e.trackingParams?g.PC(e.trackingParams):null,Xk:f.trackingParams?g.PC(f.trackingParams):null,Vf:l&&l.trackingParams?g.PC(l.trackingParams):null,SD:B4(e.playlistThumbnail.thumbnails,258).url,customMessage:e.customMessage?g.uC(e.customMessage):null,playlistVideoCount:g.uC(e.playlistVideoCount),title:e.playlistTitle?g.uC(e.playlistTitle):"",metaInfo:[e.channelName?g.uC(e.channelName):
"",e.videoCountText?g.uC(e.videoCountText):""],url:q4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Vcb(e.action)}),onClickCommand:null};z4(a,b)}else{var p;if(null==(p=b.content)?0:p.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;var q;e=null==(q=b.content)?void 0:q.videoInfoCardContentRenderer;f=b.teaser.simpleCardTeaserRenderer;l=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.I,type:"video",teaserText:g.uC(f.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),
startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,sessionData:A4(a,c,b,e),sponsored:!1,Qi:w4(e,f,e.action),qo:e.trackingParams?g.PC(e.trackingParams):null,Xk:f.trackingParams?g.PC(f.trackingParams):null,Vf:l&&l.trackingParams?g.PC(l.trackingParams):null,SD:B4(e.videoThumbnail.thumbnails,258).url,videoDuration:e.lengthString?g.uC(e.lengthString):null,customMessage:e.customMessage?g.uC(e.customMessage):null,title:e.videoTitle?g.uC(e.videoTitle):"",metaInfo:[e.channelName?g.uC(e.channelName):
"",e.viewCountText?g.uC(e.viewCountText):""],isLiveNow:!!e.badge,url:q4({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:Vcb(e.action)}),onClickCommand:null};z4(a,b)}}}}}a.I++},B4=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},A4=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},$cb=function(a,b){if(b=Zcb(a,b))b===a.j&&(a.j=null),a.F.removeCueRange(b.dg.id),g.Xe(b.tK),g.qb(a.cards,b),a.RE(),D4(a)},x4=function(a,b,c){if(!a.B){a.jb.show();
a.Ta=new g.qo(function(){g.yo(a.context.F.getRootNode(),g.yW.IV_DRAWER_OPEN)},0);
a.Ta.start();a.Ra.S(a.u,"mousewheel",function(h){a.ya.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.u.scrollTop+=h});
a.B=!0;var d=g.TC();d&&a.Fa&&a.J&&g.fN(d,[a.Fa,a.J]);b={TRIGGER_TYPE:b};for(var e=g.t(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.UU||(f.UU=!0,adb(a.context.logger,f.dg.Qi.kU,b)),d&&g.fN(d,[f.dg.qo]);$3(a.F);c&&(a.D=new g.qo(function(){a.Ja=a.T;a.Fb.focus()},330),a.D.start())}},y4=function(a){a.B&&(a.jb.hide(),g.mB(a.Ra),g.Ao(a.context.F.getRootNode(),g.yW.IV_DRAWER_OPEN),a.B=!1,$3(a.F),a.D&&a.D.stop(),a.D=new g.qo(function(){a.Ja&&(a.Ja.focus(),a.Ja=null)},330),a.D.start())},cdb=function(a){g.zo(a.xb(),
[g.yW.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.oR(a.F,a.C,5);bdb(a);a.T=g.He("ytp-cards-button",a.F.getRootNode());a.Fb=g.He("iv-drawer-close-button",a.C);a.isInitialized=!0},bdb=function(a){var b=g.He("iv-drawer-close-button",a.C);
a.context.j.Qa(b,"click",a.l2,a);a.context.j.Qa(a.u,"touchend",function(){a.ya.start()});
a.context.j.Qa(a.u,"scroll",a.F2,a);a.context.u.subscribe("onHideControls",function(){a.Ma=!0});
a.context.u.subscribe("onShowControls",function(){a.Ma=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.Ma=g.xo(a.F.getRootNode(),"ytp-autohide")});
a.ea.push(g.tA("iv-button-shown",a.w4,a));a.ea.push(g.tA("iv-button-hidden",a.v4,a));a.ea.push(g.tA("iv-teaser-shown",a.uZ,a));a.ea.push(g.tA("iv-teaser-hidden",a.x4,a));a.ea.push(g.tA("iv-teaser-clicked",a.tZ,a))},ddb=function(a,b){var c;
return b.onClickCommand&&"engagement-panel-error-corrections"===(null==(c=g.K(b.onClickCommand,g.Z9a))?void 0:c.targetId)?(a.oa=b,!0):!1},edb=function(a,b){a.oa=b;
var c=a.F.getVideoData();if(!c)return!1;c=a.F.K("embeds_web_enable_video_data_refactoring_offline_and_progress_bar")?g.QJ(c):c.multiMarkersPlayerBarRenderer;if(null==c?0:c.markersMap)for(var d,e=0;(null==(d=c)?void 0:d.markersMap.length)>e;e++){var f=void 0,h=null==(f=c)?void 0:f.markersMap[e];if("ERROR_CORRECTION_MARKERS"===h.key&&(f=void 0,(h=null==(f=h.value)?void 0:f.markers)&&0<h.length))return d=void 0,b.startMs=(null==(d=g.K(h[0],g.pOa))?void 0:d.timeRangeStartMillis)||0,a.oa=null,!0}return!1},
z4=function(a,b){if(!ddb(a,b)||edb(a,b)){var c=fdb(a,b);
if(c){var d={dg:b,tK:c.element,UU:!1};if(!b.onClickCommand){a.isInitialized||cdb(a);$cb(a,b.id);var e=gdb(a,d);g.xb(a.cards,e,0,d);c.Ea(a.u,e);a.RE()}b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.B||(a.j=d,D4(a),hdb(a,d),x4(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.F.getCurrentTime(),5E3>c&&c>b.startMs&&idb(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){idb(a,d)}),D4(a))}}},fdb=function(a,b){switch(b.type){case "simple":var c=a.Aa;
var d=b.displayDomain?{G:"div",N:"iv-card-image-text",qa:b.displayDomain}:void 0;var e=Rcb(b);d={G:"div",Ia:["iv-card"],W:[{G:"a",N:"iv-click-target",X:{href:b.url?p4(b.url)||"":""},W:[s4(b.imageUrl,d),{G:"div",N:"iv-card-content",W:[r4("h2",void 0,b.title),e]}]}]};d=new g.T(d);t4(c,g.De("iv-click-target",d.element),b,b.url);b=d;break;case "collaborator":c=a.Aa;d={G:"div",Ia:["iv-card","iv-card-channel"],W:[{G:"a",Ia:["iv-click-target"],X:{href:p4(b.url)||"","data-ytid":b.channelId},W:[s4(b.zW),{G:"div",
N:"iv-card-content",W:[Pcb(b),{G:"h2",N:"iv-card-primary-link",qa:b.title},Qcb(b)]}]}]};d=new g.T(d);t4(c,g.De("iv-click-target",d.element),b,b.url);b=d;break;case "playlist":c=a.Aa;d={G:"div",Ia:["iv-card","iv-card-playlist"],W:[{G:"a",N:"iv-click-target",X:{href:p4(b.url)||""},W:[s4(b.SD,{G:"div",N:"iv-card-image-overlay",W:[{G:"span",N:"iv-card-playlist-video-count",qa:b.playlistVideoCount}]}),{G:"div",N:"iv-card-content",W:[Pcb(b),r4("h2","iv-card-primary-link",b.title),Qcb(b)]}]}]};d=new g.T(d);
t4(c,g.De("iv-click-target",d.element),b,b.url);b=d;break;case "productListing":c=a.Aa;var f=!g.ob(b.offers);d=["iv-card"];e="";var h=Rcb(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",h=b.offers[0],f=[],h.price&&f.push({G:"div",N:"iv-card-offer-price",qa:h.price}),h.merchant&&f.push({G:"div",N:"iv-card-offer-merchant",qa:h.merchant}),h={G:"div",W:f});f=b.url?p4(b.url)||"":"";d={G:"div",Ia:d,X:{tabindex:"0"},W:[{G:"a",Ia:["iv-card-image","iv-click-target"],X:{style:"background-image: url("+
b.imageUrl+");",href:f,"aria-hidden":"true",tabindex:"-1"}},{G:"div",N:"iv-card-content",W:[b.sponsored?{G:"div",N:"iv-card-sponsored",W:["\u0420\u0435\u043a\u043b\u0430\u043c\u0430",{G:"div",N:"iv-ad-info-container",W:[{G:"div",N:"iv-ad-info",qa:"{{adInfo}}"},{G:"div",N:"iv-ad-info-icon-container",W:[{G:"div",N:"iv-ad-info-icon"},{G:"div",N:"iv-ad-info-callout"}]}]}]}:"",{G:"a",N:"iv-click-target",X:{href:f},W:[r4("h2",e,b.title),h]}]}]};d=new g.T(d);e=g.Ne("span");g.$e(e,"\u042d\u0442\u043e \u043a\u043e\u043d\u0442\u0435\u043a\u0441\u0442\u043d\u0430\u044f \u0440\u0435\u043a\u043b\u0430\u043c\u0430. \u0415\u0435 \u043f\u043e\u043a\u0430\u0437 \u043c\u043e\u0436\u0435\u0442 \u043e\u043f\u043b\u0430\u0447\u0438\u0432\u0430\u0442\u044c\u0441\u044f \u043f\u0440\u043e\u0434\u0430\u0432\u0446\u043e\u043c.");
d.le(e,"adInfo");t4(c,g.De("iv-click-target",d.element),b,b.url);b=d;break;case "video":c=a.Aa;d=b.videoDuration?{G:"span",N:"iv-card-video-duration",qa:b.videoDuration}:void 0;e=b.isLiveNow?{G:"span",Ia:["yt-badge","yt-badge-live"],qa:"\u0421\u0415\u0419\u0427\u0410\u0421 \u0412 \u041f\u0420\u042f\u041c\u041e\u041c \u042d\u0424\u0418\u0420\u0415"}:null;f={G:"div",Ia:["iv-card","iv-card-video"],W:[{G:"a",N:"iv-click-target",X:{href:(null==(h=b.url)?void 0:p4(h))||""},W:[s4(b.SD,d),{G:"div",N:"iv-card-content",
W:[Pcb(b),r4("h2","iv-card-primary-link",b.title),Qcb(b),e]}]}]};d=new g.T(f);t4(c,g.De("iv-click-target",d.element),b,b.url);b=d;break;default:return null}a.F.V().experiments.qb("web_rounded_containers")&&g.yo(b.element,"ytp-rounded-info");return b},gdb=function(a,b){if(0===a.cards.length)return 0;
a=g.lb(a.cards,function(c){return b.dg.startMs>c.dg.startMs||b.dg.startMs===c.dg.startMs&&b.dg.timestamp>=c.dg.timestamp?!0:!1});
return-1===a?0:a+1},jdb=function(a){return a.j?"productListing"===a.j.dg.type:g.$k(a.cards,function(b){return"productListing"===b.dg.type})},D4=function(a){g.Co(a.F.getRootNode(),"ytp-cards-shopping-active",jdb(a))},idb=function(a,b){if(!g.xo(a.F.getRootNode(),"ytp-cards-teaser-shown")){if(a.j!==b){var c=g.TC(),d=a.j?a.j.dg.Vf:a.Vf;
c&&d&&g.gN(c,[d]);a.j=b;D4(a)}(c=a.isInitialized&&"none"==a.xb().style.display)||(c=a.context.F.getPlayerState(),d=0===c&&0===a.context.F.getCurrentTime(),c=!(1===c||3===c||d));c||b.dg.teaserDurationMs&&a.F.Bz(!0,{teaserText:b.dg.teaserText,durationMs:b.dg.teaserDurationMs,onClickCommand:b.dg.onClickCommand});a.kb.isActive()||((!a.B||!a.ya.isActive()&&a.Ma)&&hdb(a,b),a.kb.start(910+b.dg.teaserDurationMs))}},hdb=function(a,b){a.Y.vb?(b=new e4([0,
a.u.scrollTop],[0,b.tK.offsetTop],600,icb),a.context.B.Qa(b,"animate",function(c){a.u.scrollTop=c.y}),a.context.B.Qa(b,"finish",function(c){a.u.scrollTop=c.y}),b.play()):(g.bO(a.Y,!0),a.u.scrollTop=b.tK.offsetTop,g.bO(a.Y,!1))},E4=function(a){return a.j&&a.j.dg?a.j.dg:a.cards[0]&&a.cards[0].dg?a.cards[0].dg:null},Zcb=function(a,b){return g.jb(a.cards,function(c){return c.dg.id===b})},F4=function(a,b,c){u4.call(this,a,b);
this.annotation=c;this.isActive=!1},kdb=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},G4=function(a,b,c){F4.call(this,a,b,c);
this.u=null;this.J=!1;this.B=null;this.C=!1;this.j=this.I=this.D=null},ldb=function(a,b){var c=void 0===c?0:c;
var d=gcb(b).width;g.Pl(b,d);c=new ocb(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,hcb);g.D(a,c);a.context.B.Qa(c,"begin",function(){g.am(b,!0)});
c.play()},odb=function(a,b){if(b.channel_name){var c=a.createElement({G:"div",
Ia:["iv-branding-context-name"],qa:b.channel_name}),d=a.createElement({G:"div",Ia:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.j=new g.lT(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signInUrl,a.context.F),a.j.Ea(d));var f=a.createElement({G:"div",Ia:["iv-branding-context-subscribe-caret"]}),h=a.createElement({G:"div",Ia:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.am(h,!1);a.context.Z.K("web_rounded_containers")&&g.yo(h,"ytp-rounded-branding-context");var l=a.createElement({G:"div",Ia:["branding-context-container-outer"]});l.appendChild(h);g.Jl(l,"right",b.image_width+"px");g.Ue(a.xb(),l);a.B=new g.qo(function(){mdb(a,h,l)},500);
g.D(a,a.B);a.context.j.Qa(a.xb(),"mouseover",function(){ndb(a,h,l,f,b.image_height)});
a.context.j.Qa(a.xb(),"mouseout",function(){a.B.start()})}},ndb=function(a,b,c,d,e){a.B.stop();
if(!a.C){var f=g.$l(b);a.j||(b.style.width=g.Ol(f.width,!0),c.style.width=g.Ol(f.width,!0));g.Jl(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.Jl(d,"right","1px");a.C=!0;g.am(b,!0);a.D=new g.qo(function(){g.yo(this.xb(),"iv-branding-active")},0,a);
a.D.start()}},mdb=function(a,b,c){g.Ao(a.xb(),"iv-branding-active");
a.I=new g.qo(function(){g.am(b,!1);a.j||(c.style.width=g.Ol(0,!0))},250);
a.I.start();a.C=!1},pdb=function(a,b,c,d,e,f,h){this.j=a;
this.B=b;this.Z=c;this.videoData=d;this.logger=e;this.F=f;this.u=h},qdb=function(a,b,c){F4.call(this,a,b,c);
var d=this;this.T=this.isCollapsed=this.Y=!1;this.I=5E3;this.u=this.B=this.j=this.C=null;this.J=this.createElement({G:"div",Ia:["iv-promo-contents"]});this.D=new g.qo(function(){d.j.setAttribute("aria-hidden","true");g.am(d.B,!1);g.am(d.u,!0)},700,this);
g.D(this,this.D)},sdb=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.I=b.collapsedelay_ms||a.I;var d=["iv-promo","iv-promo-inactive"];a.xb().setAttribute("aria-hidden","true");a.xb().setAttribute("aria-label","\u041f\u0440\u043e\u0434\u0432\u0438\u0436\u0435\u043d\u0438\u0435");a.xb().tabIndex=0;var e=a.annotation.We(),f=b.image_url;if(f){var h=a.createElement({G:"div",Ia:["iv-promo-img","iv-click-target"]});f=a.createElement({G:"img",X:{src:f,"aria-hidden":"true"}});
h.appendChild(f);b.video_duration&&!b.is_live?(f=a.createElement({G:"span",N:"iv-promo-video-duration",qa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({G:"span",N:"iv-promo-playlist-length",qa:b.playlist_length.toString()}),h.appendChild(f));e&&v4(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({G:"a",N:"iv-promo-txt"}),g.ee(f,p4(e)),a.j=f):a.j=a.createElement({G:"div",N:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({G:"p",
W:[{G:"strong",qa:b.text_line_1}]});var m=a.createElement({G:"p",W:[{G:"span",N:"iv-promo-link",qa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({G:"button",Ia:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({G:"button",Ia:["iv-button","iv-promo-button"],W:[{G:"span",N:"iv-button-content",qa:f}]});var p=a.createElement({G:"div",N:"iv-promo-button-container"});p.appendChild(f);e&&v4(a,a.xb(),e,a.annotation.id,b.session_data,
void 0,c)}g.yo(a.j,"iv-click-target");e&&v4(a,a.j,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({G:"p",W:[{G:"span",qa:b.text_line_1}]}),m=a.createElement({G:"p",W:[{G:"strong",qa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({G:"span",Ia:["yt-badge","iv-promo-badge-live"],qa:"\u0421\u0415\u0419\u0427\u0410\u0421 \u0412 \u041f\u0420\u042f\u041c\u041e\u041c \u042d\u0424\u0418\u0420\u0415"})),g.yo(a.j,"iv-click-target"),e&&v4(a,a.j,e,a.annotation.id,
b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.j.appendChild(l);m&&a.j.appendChild(m);a.J.appendChild(a.j);p&&a.J.appendChild(p);c=a.createElement({G:"div",N:"iv-promo-actions"});a.u=a.createElement({G:"button",Ia:["iv-promo-expand","ytp-button"]});a.u.title="\u0420\u0430\u0437\u0432\u0435\u0440\u043d\u0443\u0442\u044c";a.context.j.Qa(a.u,"click",function(q){rdb(a,5E3,q)});
c.appendChild(a.u);g.am(a.u,!1);a.context.j.Qa(a.xb(),"mouseover",a.C3,a);a.context.j.Qa(a.xb(),"mouseout",a.B3,a);a.context.j.Qa(a.xb(),"touchend",function(q){rdb(a,5E3,q)});
a.B=a.createElement({G:"button",Ia:["iv-promo-close","ytp-button"]});a.B.title="\u0417\u0430\u043a\u0440\u044b\u0442\u044c";a.context.j.Qa(a.B,"click","cta"===a.annotation.style&&b.text_line_3?a.x3:a.w3,a);c.appendChild(a.B);g.zo(a.xb(),d);h&&(g.Ue(a.xb(),h),n&&h.appendChild(n));g.Ue(a.xb(),a.J);g.Ue(a.xb(),c)},rdb=function(a,b,c){c.stopPropagation();
tdb(a);udb(a,b);a.j.focus()},vdb=function(a){a.isCollapsed||a.T||a.C||(g.yo(a.xb(),"iv-promo-collapsed"),a.isCollapsed=!0,a.D.start())},tdb=function(a){a.D.stop();
a.isCollapsed&&(g.Bo(a.xb(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.j&&a.j.removeAttribute("aria-hidden"),g.am(a.u,!1),g.am(a.B,!0))},udb=function(a,b){a.C||(a.C=g.xf(function(){wdb(this);
vdb(this)},b,a))},wdb=function(a){a.C&&(g.Ea.clearTimeout(a.C),a.C=null)},xdb=function(a){this.F=a},adb=function(a,b,c){b&&(c?H4(a,b.map(function(d){return g.jo(d,c)})):H4(a,b))},H4=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.t(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Jz(m,f);d&&(e++,0!==d&&a.F.sendVideoStatsEngageEvent(d,f))},ydb=function(a){g.hS.call(this,a);
var b=this;this.ea=this.J=!1;this.loadNumber=0;this.I={};this.logger=new xdb(this.player);this.C=new g.nG(this);this.D=this.mw=null;this.events=new g.nG(this);this.T=this.j=null;this.Y=[];g.D(this,this.C);this.C.S(this.player,"onVideoAreaChange",function(){b.ma("onVideoAreaChange")});
this.C.S(this.player,"onHideControls",function(){b.ma("onHideControls")});
this.C.S(this.player,"onShowControls",function(){b.ma("onShowControls")});
this.C.S(this.player,"resize",function(d){b.ma("resize",d)});
this.C.S(this.player,"presentingplayerstatechange",function(d){b.ma("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.vZ,this);this.subscribe("resize",this.PG,this);this.player.V().ya.subscribe("vast_info_card_add",this.hW,this);g.D(this,this.events);this.oa=this.createElement({G:"div",N:"video-custom-annotations"});this.u=new g.T({G:"div",Ia:["ytp-player-content","ytp-iv-player-content"]});g.D(this,this.u);g.oR(this.player,this.u.element,4);this.u.hide();this.B=new g.T({G:"div",Ia:["ytp-iv-video-content"]});g.D(this,this.B);a=this.createElement({G:"div",N:"video-annotations"});
a.appendChild(this.oa);this.B.element.appendChild(a);this.Yv()&&this.load();var c=this.createElement({G:"style"});(g.Be("HEAD")[0]||document.body).appendChild(c);g.ab(this,function(){g.Xe(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},zdb=function(a){a=a.createElement({G:"div",
Ia:["annotation","annotation-type-custom"]});g.am(a,!1);return a},Adb=function(a,b){b=!b.isCued()&&!g.S(b,1024);
g.bO(a.u,b);g.bO(a.B,b)},Bdb=function(a,b,c){a.J=!0;
a.D=g.Vw(b,c)},Cdb=function(a,b){for(var c={},d=g.t(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ja(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Cdb(a,e))}return c},Gdb=function(a){var b=a.player.getVideoData();
if(b.Ta){var c=a.player.V().ya.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.Pw(h)&&h.responseXML?h.responseXML:null)&&Ddb(a,h)}};
g.$x()&&(d.onFinish=Edb(a,d.onFinish));d.postParams={ic_only:"1"};Fdb(d,c);a.J=!0;g.Vw(b.Ta,d)}}},Fdb=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.VA&&(a.postParams.ic_coll=b.VA);b.uK&&(a.postParams.ic_xml=b.uK);b.eI&&(a.postParams.ic_track=b.eI)},Hdb=function(a){var b=new g.T({G:"div"});
g.am(b.element,!1);var c=new Wcb(a.player,b.element,I4(a));g.D(c,b);b.Ea(a.u.element);c.HD();return c},I4=function(a){if(!a.T){var b=new pcb(a);
g.D(a,b);var c=new g.Zj(a);g.D(a,c);a.T=new pdb(b,c,a.player.V(),a.player.getVideoData(),a.logger,a.player,a.Mh)}return a.T},Ddb=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.TC();if(e){var f=g.SC();f&&g.Bw(g.PDa)(void 0,e,f,[g.PC(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=Cdb(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=o4(f.type,Idb),p=o4(f.style,Jdb),q=Fcb(f.data),r=0!==q.length?JSON.parse(q):{};var w=f.action;f=Lcb;if(null==w)var x=null;else if(g.Ia(w)){l=[];for(var z=g.t(w),B=z.next();!B.done;B=z.next()){var E=f(B.value);
E&&l.push(E)}x=l}else{var G=f(w);x=G?[G]:[]}e=m&&n?new Mcb(m,n,p,x,r):null}else e=null}catch(V){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var F=zdb(f),L=null;switch(l.type){case "branding":if(f.player.V().Hd)break;f.u.element.appendChild(F);L=new G4(F,I4(f),l);break;case "promotion":g.oR(f.player,F,4),L=new qdb(F,I4(f),l)}L&&L.HD();if(f=L)g.D(a,f),a.I[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.j||(a.j=Hdb(a),g.D(a,a.j));if("card"===e.type){c=a.j;var O=e&&e.data&&e.data.card_type;
f=e.data;if(O)switch(l=f.tracking||{},l={kU:l.impression,click:l.click,close:l.close,FX:l.teaser_impression,YH:l.teaser_click},F=f.tracking_params||{},L=null,O){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Qi:l,qo:F.card?g.PC(F.card):null,Xk:F.teaser?g.PC(F.teaser):null,Vf:F.icon?g.PC(F.icon):null,channelId:f.channel_id,
customMessage:f.custom_message?f.custom_message:null,zW:f.image_url,title:f.title,metaInfo:f.meta_info,url:q4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};z4(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Qi:l,qo:F.card?g.PC(F.card):null,Xk:F.teaser?
g.PC(F.teaser):null,Vf:F.icon?g.PC(F.icon):null,SD:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:q4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};z4(c,e);break;case "productListing":f.signin_url&&(L=q4({target:"current",value:f.signin_url}));O=[];for(var U=f.offers||[],ba=0;ba<U.length;ba++)O.push(new Scb(g.ue(U[ba].merchant),g.ue(U[ba].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Qi:l,qo:F.card?g.PC(F.card):null,Xk:F.teaser?g.PC(F.teaser):null,Vf:F.icon?g.PC(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,TA:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:q4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),B7a:L,A7a:f.signin_title?f.signin_title:void 0,z7a:f.signin_message?f.signin_message:void 0,offers:O,onClickCommand:null};z4(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Qi:l,qo:F.card?g.PC(F.card):
null,Xk:F.teaser?g.PC(F.teaser):null,Vf:F.icon?g.PC(F.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,TA:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:q4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null};z4(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,
startMs:f.start_ms,autoOpen:f.auto_open||!1,sessionData:f.session_data||{},sponsored:f.sponsored||!1,Qi:l,qo:F.card?g.PC(F.card):null,Xk:F.teaser?g.PC(F.teaser):null,Vf:F.icon?g.PC(F.icon):null,SD:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:q4({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),onClickCommand:null},z4(c,e)}}else Xcb(a.j,e);c=!0}}c&&
($3(a.player),a.PG())},Kdb=function(a,b){var c=!1;
a.j||(a.j=Hdb(a),g.D(a,a.j));for(var d=g.t(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(Ycb(a.j,e.cardRenderer),c=!0);var f;!c||null!=(f=a.player.getVideoData())&&g.UK(f)||(c=a.j,d=b.headerText?g.uC(b.headerText):"",g.$e(c.Tb,d),c.T&&c.T.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.Fa=b.trackingParams?g.PC(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.PC(b.closeButton.infoCardIconRenderer.trackingParams):
null,c.Vf=b.icon.infoCardIconRenderer.trackingParams?g.PC(b.icon.infoCardIconRenderer.trackingParams):null,$3(a.player),a.PG())},Ldb=function(a,b,c,d,e){if(!a.player.V().Hd){var f=[];
b.navigationEndpoint&&g.K(b.navigationEndpoint,C4)&&g.K(b.navigationEndpoint,C4).browseId&&f.push(new Icb("openUrl","click",new Gcb("/channel/"+g.K(b.navigationEndpoint,C4).browseId,"new",!0,!0)));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&g.K(b.subscribeButton,
g.NK)){d.channel_id=g.K(b.subscribeButton,g.NK).channelId;var l;b=g.K(b.subscribeButton,g.NK);h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.uC(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.uC(b.subscriberCountText))):(b.subscriberCountText&&(e=g.uC(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.uC(b.subscriberCountWithSubscribeText)));var m,n=(null==(m=g.K(null==(l=b.signInEndpoint)?void 0:l.commandMetadata,g.V2))?void 0:m.url)||"";l={subscribeText:g.uC(b.unsubscribedButtonText),
subscribeCount:e||"",unsubscribeText:g.uC(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:n};d.standalone_subscribe_button_data=l}f=new Mcb(c,"branding","branding",f,d);l=zdb(a);a.u.element.appendChild(l);f=new G4(l,I4(a),f);f.HD();g.D(f,f);a.I[c]=f}},Edb=function(a,b){return function(){var c=g.ya.apply(0,arguments);
a.isDisposed()||a.Y.push(g.mo.Bi(function(){b.apply(null,g.u(c))}))}},Mdb=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.hR.prototype.Bz=g.ca(18,function(a,b){var c=g.CS(this.wb());c&&c.Bz(a,b)});
var b4={},c4=null;g.Sa(e4,g.Ko);g.k=e4.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.j)this.progress=0,this.coords=this.u;else if(this.fd())return!1;d4(this);this.startTime=a=g.Ra();-1==this.j&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.D=this.startTime;this.progress||this.LG();this.Cl("play");-1==this.j&&this.Cl("resume");this.j=1;var b=g.Oa(this);b in b4||(b4[b]=this);kcb();lcb(this,a);return!0};
g.k.stop=function(a){d4(this);this.j=0;a&&(this.progress=1);mcb(this,this.progress);this.Cl("stop");this.Bq()};
g.k.pause=function(){this.fd()&&(d4(this),this.j=-1,this.Cl("pause"))};
g.k.ra=function(){0==this.j||this.stop(!1);this.Cl("destroy");e4.Hf.ra.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.OI=function(){this.Cl("animate")};
g.k.Cl=function(a){this.dispatchEvent(new ncb(a,this))};
g.Sa(ncb,g.eb);g.Sa(f4,e4);f4.prototype.C=function(){};
f4.prototype.OI=function(){this.C();f4.Hf.OI.call(this)};
f4.prototype.Bq=function(){this.C();f4.Hf.Bq.call(this)};
f4.prototype.LG=function(){this.C();f4.Hf.LG.call(this)};
g.Sa(ocb,f4);ocb.prototype.C=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};var C4=new g.cq("browseEndpoint");g.v(pcb,g.C);g.k=pcb.prototype;g.k.Qa=function(a,b,c,d){c=(0,g.Pa)(c,d||this.u);a=g.$z(a,b,c);this.j.push(a);return a};
g.k.qG=function(a,b,c,d){c=(0,g.Pa)(c,d||this.u);a=g.Hqa(a,b,c);this.j.push(a);return a};
g.k.Hc=function(a){g.aA(a);g.qb(this.j,a)};
g.k.Ff=function(){g.aA(this.j);this.j.length=0};
g.k.ra=function(){this.Ff();g.C.prototype.ra.call(this)};g.v(scb,g.hS);g.k=scb.prototype;g.k.load=function(){g.hS.prototype.load.call(this);if(!i4(this)){var a=g.iCa(this.player.getVideoData());a?(a=rcb(a,tcb(this)),j4(this,a,!1)):ucb(this)}};
g.k.unload=function(){j4(this,null);this.B&&(this.B.abort(),this.B=null);g.hS.prototype.unload.call(this)};
g.k.qh=function(a,b){return i4(this)?"loadCustomEndscreenRenderer"===a?(a=rcb(b,"new"),j4(this,a),!0):null:null};
g.k.getOptions=function(){return i4(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.Eb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<Ndb.length;f++){var h=Math.abs(b.width-Ndb[f]);if(-1===e||d>=h)e=f,d=h}d=Odb[e];this.u&&g.Jl(this.u.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.j[f],
h=this.D[f],e&&h){var l=h.width*c/h.aspectRatio,m=Math.round(h.width*a.width);f=Math.round(l*a.height);var n=a.left+Math.round(h.left*a.width),p=a.top+Math.round(h.top*a.height);g.Zl(e.element,m,f);g.Pl(e.element,n,p);this.ea&&(g.Bo(e.element,Pdb),256<m||256<f?g.yo(e.element,"ytp-ce-large-round"):96<m||96<f?g.yo(e.element,"ytp-ce-medium-round"):g.yo(e.element,"ytp-ce-small-round"));g.Bo(e.element,Qdb);m=h.left+h.width/2;h=h.top+l/2;g.yo(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":
.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Bo(e.element,Odb);g.yo(e.element,d);(e=g.Ce(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.Jl(e,"height",f+"px")}}}}};
g.k.onCueRangeEnter=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())n4(this,this.endscreen.impressionUrls),(a=g.TC())&&this.endscreen.visualElement&&g.eN(a,this.endscreen.visualElement);else{a=a.getId().substring(15);var b=this.j[a],c=this.D[a];g.yo(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.yo(b,"ytp-ce-shown");n4(this,c.impressionUrls);(b=g.TC())&&g.eN(b,c.visualElement);this.player.V().I&&this.player.Na("endscreenelementshown",
a)}};
g.k.onCueRangeExit=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.j[a];g.Ao(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.Ao(b,"ytp-ce-shown");this.player.V().I&&this.player.Na("endscreenelementhidden",a)}};
g.k.T7=function(a){var b=this;a.target===window&&(new g.qo(function(){for(var c=g.t(Object.values(b.j)),d=c.next();!d.done;d=c.next())g.Bo(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var Ndb=[346,426,470,506,570,640,853,1280,1920],Odb="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Qdb=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"],Pdb=["ytp-ce-small-round","ytp-ce-medium-round","ytp-ce-large-round"];var Hcb={yma:"current",FJa:"new"};var Jcb={CLOSE:"close",dNa:"openUrl",SUBSCRIBE:"subscribe"},Kcb={dla:"click",CLOSE:"close",Zva:"hidden",ARa:"rollOut",BRa:"rollOver",WSa:"shown"};Mcb.prototype.We=function(){var a=Ncb(this,function(b){return"openUrl"===b.type&&null!=b.url});
return a?a.url:null};
var Jdb={Oga:"anchored",KY:"branding",CHANNEL:"channel",nma:"cta",dwa:"highlightText",Yza:"label",PLAYLIST:"playlist",tPa:"popup",AVa:"speech",SUBSCRIBE:"subscribe",uYa:"title",VIDEO:"video",g3a:"website"},Idb={KY:"branding",dja:"card",voa:"drawer",cwa:"highlight",LFa:"marker",xQa:"promotion",TEXT:"text",F4a:"widget"};g.v(u4,g.C);g.k=u4.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.kC(a,b,{id:c,namespace:"annotations_module"});d&&this.Za.set(a,d);e&&this.fb.set(a,e);this.context.F.Be([a])};
g.k.HD=function(){this.context.u.subscribe("resize",this.RE,this)};
g.k.xb=function(){return this.element};
g.k.QI=function(a,b,c,d,e,f){if(this.tb)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Xe(this.xb())};
g.k.RE=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=p4(a);if(f){var h=Ucb(f,a.target),l=function(){a.j&&e.context.F.pauseVideo();var m=e.context.videoData.D||!1,n=g.Hw(f||"");m&&n&&(n.v||n.list)?e.context.F.Hn(n.v,b,n.list,!1):g.PL(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);H4(this.context.logger,c,l,d);Tcb(f)||(c=g.TC(),d=b.itct,c&&d&&g.hN(c,g.PC(d)))}};
g.k.ra=function(){this.Za.clear();this.fb.clear();g.C.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.T(a);g.D(this,a);return a.element};g.v(Wcb,u4);g.k=Wcb.prototype;g.k.Cs=function(){this.oa&&z4(this,this.oa)};
g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.F.getRootNode())?(a=g.$l(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.RE=function(){var a=this.isAvailable();g.am(this.xb(),a);g.Co(this.context.F.getRootNode(),g.yW.IV_DRAWER_ENABLED,a);$3(this.F)};
g.k.destroy=function(){this.F.Bz(!1);try{this.F.getRootNode().removeChild(this.C)}catch(a){}g.uA(this.ea);g.mB(this.Ra);this.Ta&&this.Ta.dispose();this.D&&this.D.dispose();u4.prototype.destroy.call(this)};
g.k.l2=function(){if(this.B){H4(this.context.logger,E4(this).Qi.close);var a=g.TC();a&&this.J&&g.hN(a,this.J);y4(this)}};
g.k.F2=function(){g.Co(this.C,"iv-drawer-scrolled",0<this.u.scrollTop)};
g.k.w4=function(){var a=g.TC(),b=E4(this);b=b?b.Vf:this.Vf;a&&b&&g.fN(a,[b])};
g.k.v4=function(){var a=g.TC(),b=E4(this);b=b?b.Vf:this.Vf;a&&b&&g.gN(a,[b])};
g.k.uZ=function(){var a=E4(this);H4(this.context.logger,a.Qi.FX);var b=g.TC();b&&a&&g.fN(b,[a.Xk,a.Vf])};
g.k.x4=function(){var a=g.TC(),b=E4(this);a&&b&&g.gN(a,[b.Xk])};
g.k.tZ=function(a){var b=E4(this),c=g.TC();this.j?a?(a=this.context.logger,H4(a,b.Qi.YH),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.Xk&&g.hN(c,b.Xk)):(a=this.context.logger,H4(a,b.Qi.YH),a.F.sendVideoStatsEngageEvent(4,void 0),c&&b.Vf&&g.hN(c,b.Vf)):(a=this.context.logger,H4(a,b.Qi.YH),a.F.sendVideoStatsEngageEvent(4,void 0),c&&this.Vf&&g.hN(c,this.Vf))};g.v(F4,u4);F4.prototype.HD=function(){u4.prototype.HD.call(this);kdb(this)};
F4.prototype.show=function(){u4.prototype.show.call(this);var a=g.TC(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.fN(a,[g.PC(b.itct)])};
F4.prototype.hide=function(){u4.prototype.hide.call(this);var a=g.TC(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.gN(a,[g.PC(b.itct)])};g.v(G4,F4);
G4.prototype.show=function(){if(!this.isActive){F4.prototype.show.call(this);if(!this.J){g.yo(this.xb(),"iv-branding");var a=this.annotation.data;this.u=this.createElement({G:"img",Ia:["branding-img","iv-click-target"],X:{"aria-label":"\u041b\u043e\u0433\u043e\u0442\u0438\u043f \u043a\u0430\u043d\u0430\u043b\u0430",src:a.image_url,width:a.image_width,height:a.image_height}});g.am(this.u,!1);var b=this.createElement({G:"button",Ia:["branding-img-container","ytp-button"]});b.appendChild(this.u);this.xb().appendChild(b);
var c=this.annotation.We();c&&v4(this,b,c,this.annotation.id,a.session_data);odb(this,a);this.J=!0}g.am(this.xb(),!0);this.isActive=!0;this.u&&(ldb(this,this.u),g.yo(this.context.F.getRootNode(),"ytp-branding-shown"))}};
G4.prototype.hide=function(){this.isActive&&(F4.prototype.hide.call(this),g.am(this.xb(),!1),this.isActive=!1,g.Ao(this.context.F.getRootNode(),"ytp-branding-shown"))};
G4.prototype.destroy=function(){this.j&&(this.j.dispose(),this.j=null);F4.prototype.destroy.call(this)};g.v(qdb,F4);g.k=qdb.prototype;g.k.show=function(){this.isActive||(F4.prototype.show.call(this),this.Y||(sdb(this),this.Y=!0),g.am(this.xb(),!0),g.xf(function(){g.Ao(this.xb(),"iv-promo-inactive")},100,this),this.xb().removeAttribute("aria-hidden"),this.isActive=!0,wdb(this),tdb(this),udb(this,this.I))};
g.k.hide=function(){this.isActive&&(g.yo(this.xb(),"iv-promo-inactive"),this.isActive=!1,this.xb().setAttribute("aria-hidden","true"))};
g.k.QI=function(a,b,c,d,e,f){return this.isCollapsed?!1:F4.prototype.QI.call(this,a,b,c,d,e,f)};
g.k.C3=function(a){this.T=!0;rdb(this,500,a)};
g.k.B3=function(){this.T=!1;vdb(this)};
g.k.w3=function(a){a.stopPropagation();this.hide()};
g.k.x3=function(a){a.stopPropagation();wdb(this);this.isCollapsed=!0;g.yo(this.xb(),"iv-promo-collapsed-no-delay");this.D.start()};
g.k.destroy=function(){this.D.dispose();F4.prototype.destroy.call(this)};g.v(ydb,g.hS);g.k=ydb.prototype;g.k.qh=function(a,b){if(!Mdb(this.player.V().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.D7a(b))&&Ddb(this,a),!0;case "removeCustomAnnotationById":return b&&this.j&&($cb(this.j,b),$3(this.player)),!0}return null};
g.k.getOptions=function(){return Mdb(this.player.V().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.Yv=function(){var a=this.player.V(),b=this.player.getVideoData(),c=a.annotationsLoadPolicy||b.annotationsLoadPolicy;return b.D&&a.ea||a.K("embeds_enable_muted_autoplay")&&this.player.isMutedByMutedAutoplay()?!1:1===c&&!b.pR||a.ya.get(b.videoId)||g.VK(b)||g.WK(b)?!0:!1};
g.k.PG=function(){if(this.B){var a=this.player.ib().getVideoContentRect(!0);g.Zl(this.B.element,a.width,a.height);g.Pl(this.B.element,a.left,a.top)}if(this.j){var b=this.player.zk();a=this.j;b=b.width;g.Co(a.C,"iv-drawer-small",426>=b);g.Co(a.C,"iv-drawer-big",1280<=b)}};
g.k.vZ=function(a){Adb(this,a.state);g.S(a.state,2)&&(this.pk()&&this.po()&&2!==this.player.getPresentingPlayerType()&&this.Cz(!1),this.Bz(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.D=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.Pw(h)&&h.responseXML?h.responseXML:null)&&(Ddb(b,h),g.yo(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.hS.prototype.load.call(this);Adb(this,this.player.Gb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.$x()&&(a=Edb(this,a));var e={format:"XML",onFinish:a,onError:function(){b.D=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.V().ya.get(d);f&&Fdb(e,f);f=f&&(f.uK||f.VA);if(!c.Bw||f)c.Ta?Bdb(this,c.Ta,e):(this.mw=function(){if(!b.J)b.onVideoDataChange(e);var h=b.player.getVideoData();if((null==h?0:g.UK(h))&&!b.ea){var l,m;if(h=null==(l=h.jd)?void 0:null==(m=l.cards)?void 0:m.cardCollectionRenderer)Kdb(b,h),b.ea=!0}},this.player.addEventListener("videodatachange",this.mw));
g.oR(this.player,this.B.element,4);this.PG();(f=g.VK(c))&&Kdb(this,f);(f=g.WK(c))&&f.featuredChannel&&Ldb(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.onVideoDataChange=function(a){var b=this.player.getVideoData();b.Ta&&Bdb(this,b.Ta,a)};
g.k.unload=function(){this.player.Gf("annotations_module");for(var a=g.t(Object.keys(this.I)),b=a.next();!b.done;b=a.next())this.I[b.value].destroy();this.T=null;this.j&&(this.j.destroy(),this.j=null,$3(this.player));this.J=!1;this.D&&(this.D.abort(),this.D=null);this.ea=!1;this.I={};this.u.hide();g.hS.prototype.unload.call(this);this.B.detach();this.mw&&(this.player.removeEventListener("videodatachange",this.mw),this.mw=null)};
g.k.hW=function(a){a===this.player.getVideoData().videoId&&(this.loaded?Gdb(this):this.load())};
g.k.pk=function(){return!!this.j&&this.j.isAvailable()};
g.k.po=function(){return!!this.j&&this.j.B};
g.k.Cz=function(a,b,c){b=void 0===b?!1:b;this.pk();this.j&&(a?c?x4(this.j,c,b):x4(this.j,"YOUTUBE_DRAWER_AUTO_OPEN",b):y4(this.j))};
g.k.Bz=function(a,b){this.player.ma(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.ra=function(){this.player.V().ya.unsubscribe("vast_info_card_add",this.hW,this);g.Ao(this.player.getRootNode(),g.yW.IV_DRAWER_OPEN);for(var a=this.Y,b=g.mo,c=0,d=a.length;c<d;c++)b.zm(a[c]);this.Y.length=0;g.hS.prototype.ra.call(this)};
g.k.createElement=function(a){a=new g.T(a);g.D(this,a);return a.element};g.gS("annotations_module",ydb);g.gS("creatorendscreen",scb);})(_yt_player);
