(function(g){var window=this;'use strict';var Rdb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},Sdb=function(a){return g.MI(a)?g.rH(a.experiments,"web_player_caption_language_preference_stickiness_duration"):0},Tdb=function(a,b){var c=new g.gJ;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.u=a.u;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},Udb=function(a,b){var c,d,e;
return g.A(function(f){if(1==f.j)return c=a+"|"+b,g.y(f,g.Wy(),2);if(3!=f.j){d=f.u;if(!d)throw g.ty("gct");return g.y(f,g.WJ(d),3)}e=f.u;return f.return(e.get("captions",c))})},Vdb=function(a,b,c){Udb(a,b).then(function(d){d&&c(d.trackData,new g.gJ(d.metadata))})},Ydb=function(a){if(!Wdb.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Xdb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},Zdb=function(){return g.rB("yt-player-caption-display-settings")},J4=function(){this.segments=[]},$db=function(a,b){var c=g.Ab(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.pb(a.segments,c),g.pb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.xb(a.segments,c,0,b),g.xb(a.segments,c+1,0,b)))},aeb=function(a,b,c,d,e,f){g.C.call(this);
this.policy=a;this.player=b;this.Y=c;this.onLoadCallback=d;this.D=e;this.T=f;this.C=new J4;this.I=-1;this.B=this.u=this.j=null;this.J=new g.qo(this.QU,1E3,this);this.events=new g.nG(this);g.D(this,this.J);g.D(this,this.events);this.events.S(b,"SEEK_COMPLETE",this.gz);this.gz();this.QU()},beb=function(a){return a.j&&a.j.C?a.j.C+a.player.Md()<a.player.getCurrentTime():!1},ceb=function(a,b){var c=g.uF(b,a.policy,{}).We(),d={format:"RAW",
withCredentials:!0};if(a.policy.Aa){d.method="POST";var e=b.zs(),f=(0,g.sX)([120,0]);e&&g.GJ(e,g.pS);d.postBody=f}a.D&&(d.responseType="arraybuffer");a.B=g.Zw(c,d,3,100).then(function(h){a:{h=h.xhr;a.isDisposed();if(a.u){var l=!(a.D?h.response:h.responseText)||400<=h.status,m=g.Hva(h);if(m){h=g.uF(a.u,a.policy,{});a.u.Ak(h,m);ceb(a,a.u);break a}if(l)a.player.xa("capfail",{status:h.status});else if(a.player.Rh().ri("fcb_r"),m=a.u.gb[0].Oa,null!=a.onLoadCallback&&a.I!==m){l=a.u.gb[0];if(a.D)a.onLoadCallback(h.response,
1E3*(l.startTime+a.player.Md()));else a.onLoadCallback(h.responseText,1E3*(l.startTime+a.player.Md()));a.I=m}}a.u=null;a.B=null}}).Zj(function(h){a.u=null;
a.B=null;var l;a.player.xa("capfail",{status:null==(l=h.xhr)?void 0:l.status})});
a.u=b;$db(a.C,a.u.gb[0].Oa)},K4=function(a,b){g.kS.call(this,b.V());
this.u=a;this.F=b;this.B=null;this.D=!1;this.I=g.OI(this.F.V())&&!this.u.isManifestless},eeb=function(a,b){var c=[],d;
for(d in a.u.j)if(a.u.j.hasOwnProperty(d)){var e=a.u.j[d];if(g.qS(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.F.V().K("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.Sbb.get(e);null==q&&(q=deb[e]||deb[e.replace(/-/g,"_")],g.Sbb.set(e,q));h=q||h}c.push(new g.gJ({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
feb=function(a,b){return null!=b&&b in a.u.j?a.u.j[b]:null},geb=function(a,b,c){var d=[],e;
for(e in a.u.j)if(a.u.j.hasOwnProperty(e)){var f=a.u.j[e];if(g.qS(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},ieb=function(){var a=void 0;
a=void 0===a?{}:a;var b="suggest_correction"in heb?heb.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c.mA=d;var e=function(f){return function(){return String(a[f.mA])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.mA+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.mA,"gi"),e);c={mA:c.mA}}return b},L4=function(a,b,c,d,e,f,h,l,m,n){var p={};
Object.assign(p,b);Object.assign(p,a.params);Object.assign(p,c);var q={};Object.assign(q,b.De);a.params.De&&Object.assign(q,a.params.De);Object.assign(q,c.De);p.De=q;var r=1===p.oi,w=[{G:"span",N:"captions-text",X:{style:"word-wrap: normal; display: block;"}}],x,z,B;(l=l.qb("caption_edit_on_hover")&&(null==(x=n.getVideoData().getPlayerResponse())?void 0:null==(z=x.captions)?void 0:null==(B=z.playerCaptionsTracklistRenderer)?void 0:B.openTranscriptCommand))&&w.unshift({G:"button",N:"caption-edit",
X:{tabindex:"0","aria-label":ieb()},W:[{G:"svg",X:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},W:[{G:"path",X:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.T.call(this,{G:"div",N:"caption-window",X:{id:"caption-window-"+a.id,dir:r?"rtl":"ltr",tabindex:"0",lang:p.lang},W:w});var E=this;this.I=[];this.Fa=!1;this.u=a;this.Ma=
this.Ja=null;this.playerWidth=f;this.playerHeight=h;this.J=null;this.maxWidth=.96*f;this.fb=.96*h;this.j=p;this.Qc=c;this.oa=b;this.C=this.Da("captions-text");this.ac=""!==this.C.style.getPropertyValue("box-decoration-break")||""!==this.C.style.getPropertyValue("-webkit-box-decoration-break");this.Ra=jeb(d,e,f,h);this.Ec=m;l&&(this.D=this.Da("caption-edit"),this.S(this.D,"click",function(){E.Ec()}));
this.type=0;this.jb=this.Ra*keb(q);a=new g.nU(this.element,!0);g.D(this,a);a.subscribe("dragstart",this.yZ,this);a.subscribe("dragmove",this.xZ,this);a.subscribe("dragend",this.wZ,this);this.tb=this.kb=this.Tb=this.Fb=0;a="";this.j.windowOpacity&&(a=Ydb(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:!1===this.j.isVisible?"none":"","text-align":leb[this.j.textAlign]};this.ac&&(b["border-radius"]=a?this.jb/8+"px":"");(this.B=2===this.u.params.oi||
3===this.u.params.oi)&&meb(this,this.element);g.Jl(this.element,b);switch(this.j.yl){case 0:case 1:case 2:g.yo(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.yo(this.element,"ytp-caption-window-bottom")}},meb=function(a,b){var c="vertical-rl";
1===a.j.eP&&(c="vertical-lr");g.Je&&(c="vertical-lr"===c?"tb-lr":"tb-rl");g.Jl(b,"-o-writing-mode",c);g.Jl(b,"-webkit-writing-mode",c);g.Jl(b,"writing-mode",c);g.Jl(b,"text-orientation","upright");g.yo(b,"ytp-vertical-caption");3===a.u.params.oi&&(g.Jl(b,"text-orientation",""),g.Jl(b,"transform","rotate(180deg)"))},keb=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},neb=function(a,b){var c={},d=b.background?b.background:a.j.De.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.De.backgroundOpacity;d=Ydb(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.ac&&(c["box-decoration-break"]="clone",c["border-radius"]=a.jb/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Ra*keb(b)+"px";d=1;e=b.color||a.j.De.color;if(b.color||null!=b.textOpacity)e=Ydb(e),d=null==b.textOpacity?a.j.De.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.vK&&(h=e=b.vK);var l=a.Ra/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.jx()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.De.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.W3&&(c.visibility="hidden");1===b.hU&&a.B&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.QI||g.ry,3===a.u.params.oi?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.zn||2===b.zn||3===b.zn||4===b.zn||5===b.zn)if(g.QI)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.zn){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},oeb=function(a){a.J=g.Ne("SPAN");
g.Jl(a.J,{display:"block"});g.yo(a.J,"caption-visual-line");a.C.appendChild(a.J)},peb=function(a,b){var c=g.Ne("SPAN");
g.Jl(c,{display:"inline-block","white-space":"pre-wrap"});g.Jl(c,neb(a,b));c.classList.add("ytp-caption-segment");a.J.appendChild(c);c.previousElementSibling&&(g.Jl(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Jl(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},qeb=function(a,b,c){a.Fa=a.Fa||!!c;
var d={};Object.assign(d,a.j.De);Object.assign(d,c||b.j);Object.assign(d,a.Qc.De);(c=!a.J)&&oeb(a);for(var e=a.Ja&&a.Ma&&g.Wc(d,a.Ma)?a.Ja:peb(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(oeb(a),e=peb(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Te(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.QI||!g.Ll(n.children[2],"text-emphasis")||(m=a.B?"padding-right":"padding-top",g.Ll(n.children[2],"text-emphasis-position")&&(m=
a.B?"padding-left":"padding-bottom"),g.Bc?g.Jl(e,m,"1em"):g.Jl(e,m,"0.5em")))}a.Ma=d;a.Ja=e;a.I.push(b)},jeb=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>1.3*c&&(a=480),e=c/a*16);return e},M4=function(a,b,c,d){g.kS.call(this,a);
this.videoData=b;this.audioTrack=c;this.Va=d;this.C=b.sK},N4=function(a,b,c,d,e,f,h,l,m,n){L4.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},O4=function(a,b,c,d,e,f,h,l,m,n){L4.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.T=[];this.ea=this.Y=this.Ta=0;this.ya=NaN;this.pc=0;this.hc=null;this.Za=new g.qo(this.Z6,433,this);this.D&&(n.sb(this.D,this,167342),this.S(this.D,"click",function(){n.ob(p.D)}),a=new g.nU(this.element,!0),g.D(this,a),a.subscribe("hoverstart",function(){n.Ua(p.D,!0)},this));
g.yo(this.element,"ytp-caption-window-rollup");g.D(this,this.Za);g.Jl(this.element,"overflow","hidden")},reb=function(a,b){if(!b)return"";
a.B&&1!==a.u.params.eP&&(b*=-1);return"translate"+(a.B?"X":"Y")+"("+b+"px)"},seb=function(a){a.T=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.Jq,c=0,d=0,e=a.T.length-1;c<b&&-1<e;){var f=a.T[e];d+=a.B?f.offsetWidth:f.offsetHeight;c++;e--}a.T.length<b&&(d*=b/a.T.length);a.Y=d;b=Math;c=b.max;isNaN(a.ya)&&((d=a.j.Fr)?(e=g.Ne("SPAN"),g.$e(e,"\u2013".repeat(d)),g.Jl(e,neb(a,a.j.De)),a.C.appendChild(e),a.ya=e.offsetWidth,a.C.removeChild(e)):a.ya=0);d=a.C;a.ea=c.call(b,a.ya,a.pc,(a.B?d.offsetHeight:d.offsetWidth)+1)},teb=function(a,b){seb(a);
var c=a.T.reduce(function(e,f){return(a.B?f.offsetWidth:f.offsetHeight)+e},0);
c=a.Y-c;if(c!==a.Ta){var d=0<c&&0===a.Ta;b||isNaN(c)||d||(g.yo(a.element,"ytp-rollup-mode"),g.ro(a.Za));g.Jl(a.C,"transform",reb(a,c));a.Ta=c}seb(a)},P4=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.kC.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},Q4=function(a,b,c,d,e){g.kC.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},ueb=function(a){var b="_"+R4++;
return new Q4(0,0x8000000000000,0,b,a)},web=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.Pf){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=veb(l.textContent,n.textContent,p.textContent,f.textContent,h);return new P4(a,b,e,c,l,d,m)}switch(m.Pf){case 9:case 10:m.zn=1;break;case 11:m.zn=2;break;case 12:m.zn=3;break;case 13:m.zn=4;break;case 14:m.zn=5}return new P4(a,b,e,c,l.textContent||"",d,m)},veb=function(a,b,c,d,e){var f=g.jx(),h=
f?g.Ne("DIV"):g.Ne("RUBY"),l=g.Ne("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.Ne("DIV"):g.Ne("RP");a.textContent=b;h.appendChild(a);b=f?g.Ne("DIV"):g.Ne("RT");b.textContent=c;h.appendChild(b);c=e.Pf;if(10===c||11===c||12===c||13===c||14===c)if(g.Jl(b,"text-emphasis-style","filled circle"),g.Jl(b,"text-emphasis-color","currentcolor"),g.Jl(b,"webkit-text-emphasis","filled circle"),11===e.Pf||13===e.Pf)g.Jl(b,"webkit-text-emphasis-position","under left"),g.Jl(b,"text-emphasis-position","under left");c=!0;if(4===e.Pf||7===e.Pf||12===e.Pf||
14===e.Pf)g.Jl(h,"ruby-position","over"),g.Jl(h,"-webkit-ruby-position","before");else if(5===e.Pf||6===e.Pf||11===e.Pf||13===e.Pf)g.Jl(h,"ruby-position","under"),g.Jl(h,"-webkit-ruby-position","after"),c=!1;e=f?g.Ne("DIV"):g.Ne("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.Jl(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.Jl(f,"display","none"),f=f.nextElementSibling,g.Jl(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Jl(h.lastElementChild,"display","none"),d?(g.Jl(h,"padding-top","0.6em"),g.Jl(f,"top","0")):(g.Jl(h,"padding-bottom","0.6em"),g.Jl(f,"bottom","0")));return h},S4=function(){g.C.apply(this,arguments)},T4=function(a){S4.call(this);
this.C=a;this.pens={};this.T={};this.Y={};this.D="_"+R4++;this.J={};this.B=this.j=null;this.I=!0},U4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},V4=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},W4=function(a,b){a=U4(a,b);
return void 0!==a?a:null},Y4=function(a,b){a=a.getAttribute(b);
if(null!=a)return X4.test(a),a},xeb=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.Y[d]:a.C);a=W4(b,"mh");null!=a&&(c.Vy=a);a=W4(b,"ju");null!=a&&(c.textAlign=a);a=W4(b,"pd");null!=a&&(c.oi=a);a=W4(b,"sd");null!=a&&(c.eP=a);a=Y4(b,"wfc");null!=a&&(c.windowColor=a);b=U4(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},yeb=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.T[d]);a=W4(b,"ap");null!=a&&(c.yl=a);a=U4(b,"cc");null!=a&&(c.Fr=a);a=U4(b,"ah");null!=a&&(c.Lj=a);a=U4(b,"rc");null!=a&&(c.Jq=a);b=U4(b,"av");null!=b&&(c.An=b);return c},zeb=function(a,b,c,d){var e={};
Object.assign(e,yeb(a,b));Object.assign(e,xeb(a,b));d?g.Wc(e,a.C)?(d=a.D,e=a.C):d="_"+R4++:d=b.getAttribute("id")||"_"+R4++;a=U4(b,"t")+c;b=U4(b,"d")||0x8000000000000;if(2===e.oi||3===e.oi)c=e.Jq,e.Jq=e.Fr,e.Fr=c;return new Q4(a,b,0,d,e)},Z4=function(a){S4.call(this);
this.I=a;this.j=new Map;this.C=new Map;this.D=new Map;this.B=new Map},$4=function(a){a=g.ie(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},Aeb=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.C.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.D.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Jq=a);b=b.ccColCount;void 0!==b&&(f.Fr=b);if(2===f.oi||3===f.oi)b=f.Jq,f.Jq=f.Fr,f.Fr=b;return new Q4(c,d,0,e,f)},Ceb=function(){this.B=this.time=this.mode=this.u=0;
this.C=new Beb(this);this.D=new Beb(this);this.j=[];this.clear()},Eeb=function(a,b,c){if(255===a&&255===b||!a&&!b)return{ou:a,
Br:b,result:0};a=Deb[a];b=Deb[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.Ee()&&c.Br===d;if(d)return{ou:a,Br:b,result:1}}else if(b&128&&1<=a&&31>=a)return{ou:a,Br:b,result:2};return{ou:a,Br:b,result:3}},Geb=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.B&&a.reset(),a.C.u.clear(),a.D.u.clear()):(a.B=0,Feb(a.C,b,c,d))},Heb=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.t(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?Geb(a,d.mS,d.nS,b):1===d.type&&a.u&496&&Feb(a.D,d.mS,d.nS,b);a.j.length=0},a5=function(){this.type=0},b5=function(){this.state=this.Br=this.ou=0},Ieb=function(){this.timestamp=this.j=0},c5=function(a){this.D=a;
this.B=[];this.j=this.u=this.row=0;this.style=new a5;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new Ieb}},d5=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var r=q.timestamp;r<e&&(e=r);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),r=p.timestamp,r<=e&&(e=r),l+=n,p.reset()),32===m||0===q)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},Neb=function(a,b){switch(a){case 0:return Jeb[(b&127)-32];
case 1:return Keb[b&15];case 2:return Leb[b&31];case 3:return Meb[b&31]}return 0},e5=function(a){return a.B[a.row][a.u]},f5=function(a,b,c){2<=b&&1<a.u&&(--a.u,e5(a).j=0);
var d=e5(a);d.timestamp=a.D.time+0;d.j=Neb(b,c);32>a.u&&a.u++},Oeb=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},g5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},Peb=function(a){a.row=0<a.j?a.j:1;
a.u=1;g5(a,0,15)},Qeb=function(a){this.B=a;
this.D=0;this.style=new a5;this.I=new c5(this.B);this.J=new c5(this.B);this.text=new c5(this.B);this.u=this.I;this.C=this.J;this.j=this.u},Reb=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(d5(d,c),Peb(a.u),Peb(a.C),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.B.mode=1<<d.C;e?d.u=1:d.j!==b&&(d.j>b?(d5(d,c),g5(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},Seb=function(a){a.style.set(1);
a.j=a.C;a.j.j=0;a.j.style=a.style;a.B.mode=1<<a.j.C},Teb=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.B.mode=1<<a.j.C},Beb=function(a){this.j=a;
this.D=0;this.B=new Qeb(this.j);this.I=new Qeb(this.j);this.u=new b5;this.C=this.B},Feb=function(a,b,c,d){a.u.update();
b=Eeb(b,c,a.u);switch(b.result){case 0:return;case 1:case 2:return}var e=b.ou;c=b.Br;if(32<=e||!e)a.j.mode&a.j.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.C.j,b&96&&f5(a,0,b),c&96&&f5(a,0,c),0!==b&&0!==c&&3===a.style.type&&d5(a,d));else if(e&16)a:if(!a.u.matches(e,c)&&(b=a.u,b.ou=e,b.Br=c,b.state=2,b=e&8?a.I:a.B,a.C=b,a.j.mode=1<<(a.D<<2)+(b.D<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.D<<2)+(b.D<<1)+(4!==b.style.type?1:0))&a.j.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;Oeb(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));g5(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:f5(b.j,0,32);break a;case 48:57===c?(d=b.j,e5(d).j=0,32>d.u&&d.u++):f5(b.j,1,c&15)}break;case 2:c&32&&f5(b.j,2,c&31);break;case 3:c&32&&f5(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Seb(b);
break;case 33:d=b.j;1<d.u&&(--d.u,e5(d).j=0);break;case 36:d=b.j;b=e5(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:Reb(b,2,d);break;case 38:Reb(b,3,d);break;case 39:Reb(b,4,d);break;case 40:f5(b.j,0,32);break;case 41:b.style.set(2);b.j=b.u;b.j.j=0;b.j.style=b.style;b.B.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);Peb(d);Teb(b);break;case 43:Teb(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:d5(a,d)}g5(a,
0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;d5(a,d);Oeb(a,b,b+1,a.j-1);g5(a,a.row,1)}break;case 46:g5(b.C,0,15);break;case 47:d5(b.u,d),b.C.updateTime(b.B.time+0),d=b.C,b.C=b.u,b.u=d,Seb(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.u+=c&3)&&(d.u=32)}}},Ueb=function(){},h5=function(a,b,c){this.trackData=a;
this.I=c;this.version=this.D=this.B=this.byteOffset=0;this.j=new DataView(this.trackData);this.u=[]},i5=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},j5=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},k5=function(a,b){S4.call(this);
this.B=a;this.C=b;this.track="CC3"===this.C.languageName?4:0;this.j=new Ceb;this.j.u=1<<this.track},Web=function(a){if("string"===typeof a)return!1;
a=new h5(a,8,0);return Veb(a)},Veb=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==j5(a))return!1;
a.version=i5(a);if(1<a.version)return!1;i5(a);i5(a);i5(a);return!0},l5=function(){S4.call(this)},Xeb=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new P4(b,c,d,e.id,p.nodeValue,f||0<n,g.Rc(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);Xeb(a,b,c,d,e,!0,p,q,m)}}},Yeb=function(a){var b=a.split(":");
a=0;b=g.t(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},Zeb=function(a,b,c,d){d=Object.assign({Vy:0},d);
return new Q4(a,b,c,"_"+R4++,d)},m5=function(a,b){g.C.call(this);
this.F=a;this.Z=b;this.parser=null;this.j=this.F.oy()},efb=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.j&&b){var f=e,h=$eb(a,b,d),l=[];try{for(var m=g.t(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,r=p.UO;l="string"!==typeof q?l.concat(afb(a,c,q,r,f)):"WEBVTT"===q.substring(0,6)?l.concat(bfb(a,q,r)):l.concat(cfb(a,c,q,r))}var w=l}catch(x){g.PB(x),a.clear(),w=[]}if(0!==w.length)return w}b=dfb(b);if(!b)return[];try{return"string"!==typeof b?afb(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?bfb(a,b,d):cfb(a,c,b,d)}catch(x){return g.PB(x),a.clear(),[]}},dfb=function(a){if("string"===
typeof a||Web(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.xE(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.iE(a)},$eb=function(a,b,c){if("string"===typeof b||Web(b))return[{trackData:b,
UO:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.vua(d);if(a.j&&e){var f=g.nua(e),h=g.oua(e);e=e.j;f&&e&&a.j.WD(e,f,h)}a=g.GE(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.iE(e),f.push({trackData:e,UO:c+1E3*h});ffb(d,f,c);return f=f.filter(function(l){return!!l.trackData})},ffb=function(a,b,c){var d=g.xE(a,0,1836476516),e=9E4;
d&&(e=g.yE(d)||9E4);d=0;for(var f=g.GE(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.xE(a,l.dataOffset,1953653094))&&(l=g.xE(a,l.dataOffset,1952867444))&&(l=g.EE(l)/e*1E3,0===h&&(d=l),b[h].UO=l-d+c||c*h*1E3)}},afb=function(a,b,c,d,e){if(!Web(c))throw Error("Invalid binary caption track data");
a.parser||(a.parser=new k5(e,b));return a.parser.u(c,d)},bfb=function(a,b,c){a.parser||(a.parser=new l5);
a=a.parser.u(b,c);.01>Math.random()&&g.QB(Error("Deprecated subtitles format in web player: WebVTT"));return a},cfb=function(a,b,c,d){if("{"===c[0])try{return a.parser||(a.parser=new Z4(gfb(b))),a.parser.u(c,d)}catch(f){return g.PB(f),[]}var e=g.D7a(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.parser||(a.parser=new T4(gfb(b),a.Z)),a.parser.u(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},gfb=function(a){var b=
{};
if(a=g.jJ(a))b.lang=a,g.E9a.test(a)&&(b.oi=1);return b},n5=function(a){g.hS.call(this,a);
var b=this;this.F=a;this.Z=this.F.V();this.videoData=this.F.getVideoData();this.tb=this.F.ib();this.B={De:{}};this.D={De:{}};this.Fa=[];this.ea={};this.Ta={};this.Aa=!1;this.ac=g.fL(this.videoData);this.jb=g.RLa(this.videoData,this.F);this.pc=!!this.videoData.captionTracks.length;this.hc=!!this.videoData.oe;this.Za="3"===this.Z.controlsType;this.u=this.J=this.T=this.Ra=this.kb=null;this.fb=new m5(this.F,this.Z);this.j=null;this.ya=new g.nG(this);this.I=new g.T({G:"div",N:"ytp-caption-window-container",
X:{id:"ytp-caption-window-container"}});this.Y={top:0,right:0,bottom:0,left:0,width:1,height:1};var c=null,d=g.mp("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Vo(d));this.storage=c;var e;this.Fb=!(null==(e=a.ye())||!e.QD());this.C=hfb(this);this.oa=!this.C&&this.Za&&this.Fb&&this.jb;g.D(this,this.fb);this.C?this.Ma=this.Ja=null:(this.Ja=new g.oo(this.uP,void 0,this),g.D(this,this.Ja),this.Ma=new g.qo(this.z8,2E3,this),g.D(this,this.Ma));g.D(this,this.ya);g.oR(this.player,this.I.element,
4);g.D(this,this.I);this.C||this.ya.S(a,"resize",this.xP);(this.Tb=g.tI(this.Z)&&!g.gB()&&!this.F.isFullscreen()&&!this.C&&!this.oa)&&this.ya.S(a,"resize",this.j6);this.ya.S(a,"onPlaybackAudioChange",this.x5);this.ya.S(a,g.mC("captions"),function(f){b.onCueRangeEnter(f)});
this.ya.S(a,g.nC("captions"),function(f){b.onCueRangeExit(f)});
ifb(this,Zdb()||{});this.player.Na("onCaptionsModuleAvailable")},lfb=function(a){if(1===a.Z.Fb||1===a.videoData.yC||"alwayson"===g.LK(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().u;if(2===a.Z.Fb){if(g.MI(a.Z))var c=jfb(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(null!=c)return!!c}c=Rdb(a.player.getAudioTrack(),g.MI(a.Z));var d=g.LK(a.videoData,"yt:cc");if(void 0===kfb(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===
b||"on"===g.LK(a.videoData,"yt:cc")},o5=function(a,b){if(a.j&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.j||"FORCED_ON"===a.u},kfb=function(a){var b=void 0,c=g.Nx(g.Mx(),65);
if(g.MI(a.Z)&&null!=c){if(null!=jfb(a))return!1;b=!c}return b},mfb=function(a){var b;
a.ac?b=new M4(a.Z,a.videoData,a.player.getAudioTrack(),a.player):a.jb?b=new K4(a.videoData.j,a.player):a.pc?b=new g.lS(a.Z,a.videoData,a.player.getAudioTrack()):b=new g.rS(a.Z,a.videoData.oe,a.videoData.videoId,g.nCa(a.videoData),a.videoData.jm,a.videoData.eventId);return b},q5=function(a,b){if(a.u){if(a.J&&a.J.C)return a.J.C;
g.YK(a.videoData)&&(b=!0);b||(b=a.hc?!1:a.pc?!1:!0);b=b||nfb(a);b=g.iS(a.u.j,b);var c=null;if(Sdb(a.Z)){var d=a.F.isInline()?void 0:g.rB("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.Z.captionsLanguagePreference,g.LK(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.jJ(b[m])===l)return b[m];l=l.split("-")[0];for(m=0;m<b.length;m++)if(g.jJ(b[m])===l)return b[m]}}if(a.Z.K("web_player_always_enable_auto_translation")&&
f&&a.u&&(e=a.u.C,e.length))for(e=g.t(e),f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.Z.captionsLanguagePreference,g.LK(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.jJ(b[f])===d[e])return b[f];d=null;a.J&&a.J.B&&(d=a.J.B);d||(d=b.find(function(n){return n.isDefault})||null);
d||(d=b[0]||p5(a));d&&c&&(d=Tdb(d,c));return d}return null},p5=function(a){return a.J&&a.J.j},r5=function(a){var b=p5(a);
return!!b&&a.j===b},ofb=function(a){g.iS(a.u.j,!0);
var b=Rdb(a.player.getAudioTrack(),g.MI(a.Z)),c;"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=q5(a,a.Aa):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&o5(a)?c=p5(a):kfb(a)||a.Aa||lfb(a)?c=q5(a,a.Aa):o5(a)&&(c=p5(a));if(a.C||a.oa){var d=g.iS(a.u.j,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.Ne("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.hJ(f));h.setAttribute("srclang",g.jJ(f));h.setAttribute("id",f.toString());a.oa||h.setAttribute("src",a.u.Qu(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.F.ye();c.NA(b);c=c.xb();a.Fb&&a.ya.S(c.textTracks,"change",a.G7)}else!a.j&&c&&s5(a,c),a.player.Na("onCaptionsTrackListChanged"),a.player.Na("onApiChange")},pfb=function(a,b){var c=a.F.ye().xb().textTracks;
a=a.j.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},s5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.Aa=c,a.Aa&&(g.MI(a.Z)?t5(a,!!b):u5(a,!!b)));a.j=b;o5(a)&&(a.j=p5(a));a.load()},rfb=function(a,b){if(b instanceof Q4){var c=a.ea[b.id];
c&&c.u!==b&&(c.dispose(),delete a.ea[b.id],c=null);c||(c=qfb(a,b))&&(a.ea[b.id]=c)}else c=b.windowId,a.Ta[c]||(a.Ta[c]=[]),a.Ta[c].push(b)},qfb=function(a,b){var c=sfb(a);
if(!c)return null;var d=a.j?g.jJ(a.j):null;d&&g.E9a.test(d)&&(b.params.oi=1);var e=a.tb.getPlayerSize();d=e.height*a.Y.height;e=e.width*a.Y.width;"google-live"!==a.Z.playerStyle||a.B.isDefault||Object.assign(b.params,a.B);switch(null!=b.params.Vy?b.params.Vy:1<b.j.length?1:0){case 1:return new N4(b,a.B,a.D,c.width,c.height,e,d,a.Z.experiments,a.RI.bind(a),a.F);case 2:return new O4(b,a.B,a.D,c.width,c.height,e,d,a.Z.experiments,a.RI.bind(a),a.F);default:return new L4(b,a.B,a.D,c.width,c.height,e,d,
a.Z.experiments,a.RI.bind(a),a.F)}},ifb=function(a,b,c){c=void 0===c?!1:c;
var d=v5.De;a.B={};Object.assign(a.B,v5);a.B.De={};Object.assign(a.B.De,d);a.D={De:{}};var e=b.backgroundOverride?a.D:a.B,f=b.background||d.background;X4.test(f);e.De.background=f;e=b.colorOverride?a.D:a.B;f=b.color||d.color;X4.test(f);e.De.color=f;e=b.windowColorOverride?a.D:a.B;f=b.windowColor||v5.windowColor;X4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.D:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.De.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.D:a.B;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.De.fontSizeIncrement=f;f=b.fontStyleOverride?a.D:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.De;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.D:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.De.textOpacity=f;e=b.windowOpacityOverride?a.D:a.B;f=b.windowOpacity;null==f&&(f=v5.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.D:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.De.charEdgeStyle=f;e=b.fontFamilyOverride?a.D:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.De.fontFamily=f;a.loaded&&a.xP();c&&g.qB("yt-player-caption-display-settings",b,2592E3)},ufb=function(a,b,c){b&&!a.T?(b=ueb({oi:0,
lang:"ru"}),a.T=[b,new P4(b.start,b.end-b.start,0,b.id,null!=c?c:"\u0421\u0443\u0431\u0442\u0438\u0442\u0440\u044b \u0431\u0443\u0434\u0443\u0442 \u0432\u044b\u0433\u043b\u044f\u0434\u0435\u0442\u044c \u0442\u0430\u043a")],a.player.Be(a.T)):!b&&a.T&&(tfb(a,a.T),a.T=null)},tfb=function(a,b){a.player.Ch(b);
b=g.t(b);for(var c=b.next();!c.done;c=b.next())g.qb(a.Fa,c.value);g.po(a.Ja)},sfb=function(a){var b=a.tb.getVideoContentRect(!0).height,c=a.tb.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.Y.height;c*=a.Y.width;return{width:c,height:b}},u5=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},t5=function(a,b){a.F.isInline()||g.qB("yt-player-sticky-caption",b,2592E3)},jfb=function(a){if(!a.F.isInline())return g.rB("yt-player-sticky-caption")},hfb=function(a){var b,c=!(null==(b=a.F.ye())||!b.PD());
return a.Za&&c&&!a.jb},nfb=function(a){return a.Z.K("web_deprecate_always_includes_asr_setting")&&g.MI(a.Z)?!0:!!g.Nx(g.Mx(),66)};
g.bW.prototype.yB=g.ca(40,function(a){var b=2;this.Za.has(a)?b=0:g.JQa(this,a)&&(b=1);return b});
g.eY.prototype.yB=g.ca(39,function(a){return this.Gd.yB(a)});
g.bW.prototype.WD=g.ca(38,function(a,b,c){this.Ja.set(a,{Gu:b,LA:c})});
g.eY.prototype.WD=g.ca(37,function(a,b,c){this.Gd.WD(a,b,c)});
g.kS.prototype.WN=g.ca(30,function(){return!1});
g.kS.prototype.Ns=g.ca(29,function(){});
g.lS.prototype.Ns=g.ca(28,function(a,b,c){var d=this;this.isDisposed();b=this.Qu(a,b);this.Xq();this.u=g.Vw(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.rS.prototype.Ns=g.ca(27,function(a,b,c){var d=this;this.isDisposed();b=this.Qu(a,b);this.Xq();this.u=g.Vw(b,{format:"RAW",onSuccess:function(e){d.u=null;c(e.responseText,a)},
withCredentials:!0})});
g.OR.prototype.Hx=g.ca(26,function(){for(var a=g.Ce(document,"track",void 0,this.j),b=0;b<a.length;b++)g.Xe(a[b])});
g.PV.prototype.Hx=g.ca(25,function(){this.mediaElement.Hx()});
g.OR.prototype.QD=g.ca(24,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.PV.prototype.QD=g.ca(23,function(){return this.mediaElement.QD()});
g.OR.prototype.PD=g.ca(22,function(){return!!this.j.textTracks});
g.PV.prototype.PD=g.ca(21,function(){return this.mediaElement.PD()});
g.OR.prototype.NA=g.ca(20,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.PV.prototype.NA=g.ca(19,function(a){this.mediaElement.NA(a)});
g.YX.prototype.PB=g.ca(9,function(){return this.I});
g.hZ.prototype.PB=g.ca(8,function(){var a;return(null==(a=g.VQ(this))?void 0:a.oy())||null});
g.hR.prototype.oy=g.ca(7,function(){return this.app.PB()});
g.WY.prototype.oy=g.ca(6,function(){var a;return(null==(a=this.Ga)?void 0:a.PB())||null});
g.XD.prototype.SF=g.ca(2,function(a){return(a=this.Eo(a))?a.j:0});
g.MF.prototype.SF=g.ca(1,function(){return 0});
var Xdb=/#(.)(.)(.)/,Wdb=/^#(?:[0-9a-f]{3}){1,2}$/i,deb={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",
chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",
li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaq",
min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",
nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",
pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",
sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",
sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",
ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",
ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};J4.prototype.contains=function(a){a=g.Ab(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
J4.prototype.length=function(){return this.segments.length/2};
g.v(aeb,g.C);g.k=aeb.prototype;g.k.ra=function(){g.C.prototype.ra.call(this);this.B&&this.B.cancel()};
g.k.gz=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Md();var b=this.j;this.j=g.fb(this.Y.ys(a).gb);b!==this.j&&this.T&&this.T()};
g.k.reset=function(){this.C=new J4;this.I=-1;this.B&&(this.B.cancel(),this.B=null)};
g.k.QU=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.vr(a);if(a&&!this.B&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.CA(a);var b;if(null==(b=this.player.getVideoData())?0:b.enableServerStitchedDai)if(b=this.player.oy()){var c=a.gb[0].j.info.id,d=a.gb[0].Oa,e=a.gb[0].B;if(this.policy.Aa){if(b=b.zs(e,d,c,3))a.J=b}else if(c=b.Dm(e,d,c,3))if(b=b.yB(d),0===b)c&&(a.u=new g.QD(c));else if(2===b){this.J.start();beb(this)&&this.seekTo(this.player.getCurrentTime());
return}}a.gb[0].duration?(this.C.contains(a.gb[0].Oa)||ceb(this,a),this.j=g.fb(a.gb)):beb(this)&&this.seekTo(this.player.getCurrentTime())}this.J.start()};
g.v(K4,g.kS);g.k=K4.prototype;g.k.Ns=function(a,b,c){var d=this;this.Xq();b=feb(this,a.getId());b||(b=a.languageCode,b=this.u.isManifestless?geb(this,b,"386"):geb(this,b));if(b){var e=1E3*(b.index.SF(b.index.Gm())-b.index.getStartTime(b.index.Gm())),f=new g.mS(this.Z);this.B=new aeb(f,this.F,b,function(h,l){c(h,a,l,e)},this.I||g.IF(b.info),function(){d.B&&d.B.reset();
d.D=!0})}};
g.k.WN=function(){var a=this.D;this.D=!1;return a};
g.k.Oy=function(a){var b=this.I?[new g.gJ({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.gJ({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.u.isManifestless?eeb(this,"386"):eeb(this);b=g.t(b);for(var c=b.next();!c.done;c=b.next())g.jS(this.j,c.value);a()};
g.k.Xq=function(){this.B&&(this.B.dispose(),this.B=null)};
g.k.Qu=function(){return""};
var X4=/^#(?:[0-9a-f]{3}){1,2}$/i,heb=window.yt&&window.yt.msgs_||window.ytcfg&&window.ytcfg.msgs||{};g.Fa("yt.msgs_",heb);var leb=["left","right","center","justify"];g.v(L4,g.T);g.k=L4.prototype;g.k.yZ=function(a,b){this.kb=a;this.tb=b;var c=g.Sl(this.element,this.element.parentElement);this.Fb=a-c.x;this.Tb=b-c.y};
g.k.xZ=function(a,b){if(a!==this.kb||b!==this.tb){g.xo(this.element,"ytp-dragging")||g.yo(this.element,"ytp-dragging");var c=g.$l(this.element);a=a-this.Fb-.02*this.playerWidth;var d=b-this.Tb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.ie(e,0,2));var f=(d+c.height/2)/this.fb*3;f=Math.floor(g.ie(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.ie(a,0,1);c=(d+f/2*c.height)/this.fb;c=100*g.ie(c,0,1);this.u.params.yl=b;this.u.params.An=c;this.u.params.Lj=a;this.u.params.isDefault=
!1;this.j.yl=b;this.j.An=c;this.j.Lj=a;this.j.isDefault=!1;this.oa.yl=b;this.oa.An=c;this.oa.Lj=a;this.oa.isDefault=!1;this.UW()}};
g.k.wZ=function(){g.Ao(this.element,"ytp-dragging")};
g.k.UW=function(){this.Iz(this.I)};
g.k.getType=function(){return this.type};
g.k.Iz=function(a){var b=Math.min(this.oT(),this.maxWidth),c=this.nT(),d="";3===this.u.params.oi&&(d="rotate(180deg)");g.Jl(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.cK(a);d={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.Lj+2,f=this.j.yl;switch(f){case 0:case 3:case 6:(b=this.j.De.fontSizeIncrement)&&0<b&&2!==this.j.oi&&3!==
this.j.oi&&(e=Math.max(e/(1+2*b),2));d.left=e+"%";break;case 1:case 4:case 7:d.left=e+"%";e=this.C.offsetWidth;b||e?(b=b||e+1,d.width=b+"px",d["margin-left"]=b/-2+"px"):d.transform+=" translateX(-50%)";break;case 2:case 5:case 8:d.right=100-e+"%"}b=.96*this.j.An+2;switch(f){case 0:case 1:case 2:d.top=b+"%";break;case 3:case 4:case 5:d.top=b+"%";(c=c||this.element.clientHeight)?(d.height=c+"px",d["margin-top"]=c/-2+"px"):d.transform+=" translateY(-50%)";break;case 6:case 7:case 8:d.bottom=100-b+"%"}g.Jl(this.element,
d);if(this.D){c=this.C.offsetHeight;d=1;for(f=0;f<a.length;f++)b=a[f],"string"===typeof b.text&&(d+=b.text.split("\n").length-1,b.append||0===f||d++);c/=d;this.D.style.height=c+"px";this.D.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=c+"px"}};
g.k.cK=function(a){var b;for(b=0;b<a.length&&a[b]===this.I[b];b++);if(this.Fa||this.I.length>b)b=0,this.Fa=!1,this.I=[],this.J=this.Ma=this.Ja=null,g.Ve(this.C);for(;b<a.length;b++)qeb(this,a[b])};
g.k.oT=function(){return 0};
g.k.nT=function(){return 0};
g.k.toString=function(){return g.T.prototype.toString.call(this)};g.v(M4,g.kS);M4.prototype.Ns=function(a,b,c){Vdb(this.videoData.videoId,a.vssId,c)};
M4.prototype.Oy=function(a){if(this.audioTrack)for(var b=g.t(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.jS(this.j,c.value);a()};g.v(N4,L4);N4.prototype.cK=function(a){var b=this.u.j;L4.prototype.cK.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,vfb);var e=c.j;var f=d}qeb(this,c,d)}};
var vfb={W3:!0};g.v(O4,L4);g.k=O4.prototype;g.k.UW=function(){g.so(this.Za)};
g.k.Z6=function(){g.Ao(this.element,"ytp-rollup-mode");this.Iz(this.hc,!0)};
g.k.nT=function(){return this.B?this.ea:this.Y};
g.k.oT=function(){return this.B?this.Y:this.ea};
g.k.Iz=function(a,b){this.hc=a;if(this.u.params.Jq){for(var c=0,d=0;d<this.I.length&&c<a.length;d++)this.I[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.I.concat(a.slice(c)));this.pc=this.ea;this.Y=this.ea=0;L4.prototype.Iz.call(this,a);teb(this,b)}L4.prototype.Iz.call(this,a)};g.v(P4,g.kC);P4.prototype.toString=function(){return g.kC.prototype.toString.call(this)};g.v(Q4,g.kC);Q4.prototype.toString=function(){return g.kC.prototype.toString.call(this)};
var R4=0;g.v(S4,g.C);S4.prototype.u=function(){return[]};
S4.prototype.reset=function(){};g.v(T4,S4);T4.prototype.reset=function(){this.J={};this.B=this.j=null;this.I=!0};
T4.prototype.u=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.t(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.t(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=V4(a,"b");
null!=l&&(h.bold=l);l=V4(a,"i");null!=l&&(h.italic=l);l=V4(a,"u");null!=l&&(h.underline=l);l=W4(a,"et");null!=l&&(h.charEdgeStyle=l);l=W4(a,"of");null!=l&&(h.offset=l);l=Y4(a,"bc");null!=l&&(h.background=l);l=Y4(a,"ec");null!=l&&(h.vK=l);l=Y4(a,"fc");null!=l&&(h.color=l);l=W4(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=U4(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=U4(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=U4(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=W4(a,"rb");null!=l&&10!==l&&
0!==l&&(h.Pf=10<l?l-1:l);a=W4(a,"hg");null!=a&&(h.hU=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.Y[c]=xeb(this,a);break;case "wp":c=a.getAttribute("id"),this.T[c]=yeb(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.t(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=zeb(this,a,b,!1);(a=this.J[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.J[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.D;
h=!!V4(a,"a");l=(U4(a,"t")||0)+l;var m=U4(a,"d")||5E3;h||(!this.I&&this.B&&this.B.windowId===f&&this.B.end>l&&(this.B.end=l),this.B&&"\n"===this.B.text&&(this.B.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.I=null!=a.getAttribute("d"));for(var r=0;r<q.length;r++){var w=q[r],x=void 0;0<r&&(h=!0);var z=void 0;1===w.nodeType&&(z=w);if(z&&"s"===z.tagName){if((w=(w=z.getAttribute("p"))?this.pens[w]:null)&&w.Pf&&(1===w.Pf?(w=q.slice(r,r+
4),4===w.length&&(x=web(l,m,f,h,n,w,this.pens),r+=3)):x=web(l,m,f,h,n,[z],this.pens)),!x){var B=z;x=l;z=m;w=f;var E=h,G=n,F=B.textContent?B.textContent:"",L=B.getAttribute("p");L=L?this.pens[L]:null;B=U4(B,"t")||0;x=new P4(x+B,z-B,G,w,F,E,L)}}else x=new P4(l,m,n,f,w.textContent||"",h,p);c.push(x);this.B=x}if(0<c.length)for(c[0].windowId===this.D&&(this.j=zeb(this,a,b,!0),d.push(this.j)),a=g.t(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var wfb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.v(Z4,S4);Z4.prototype.reset=function(){this.B.clear()};
Z4.prototype.u=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.t(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.vK=$4(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=$4(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=$4(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.Pf=10<h?h-1:h,f.zn=wfb.get(f.Pf));e.hgHorizGroup&&(f.hU=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.t(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.D.get(h)):Object.assign(f,
this.I),void 0!==e.mhModeHint&&(f.Vy=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.oi=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.eP=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=$4(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.D.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.t(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.C.get(h)),void 0!==e.ahHorPos&&
(f.Lj=e.ahHorPos),void 0!==e.apPoint&&(f.yl=e.apPoint),void 0!==e.avVerPos&&(f.An=e.avVerPos),void 0!==e.ccCols&&(f.Fr=e.ccCols),void 0!==e.rcRows&&(f.Jq=e.rcRows),this.C.set(a++,f);if(c.events){a=[];c=g.t(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=Aeb(this,l,d,e,f),a.push(d),this.B.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+R4++,h=Aeb(this,l,d,e,f),a.push(h),this.B.set(f,h));0===e&&(e=5E3);h=this.B.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var r=p[l],w=r.utf8;if(w){var x=r.tOffsetMs||0,z=null;r.pPenId&&(z=this.j.get(r.pPenId));if(2===(null!=h.params.Vy?h.params.Vy:1<h.j.length?1:0)&&m&&"\n"===w)continue;if(r=z&&1===z.Pf)if(r=l,r+3>=p.length||!p[r+1].pPenId||!p[r+2].pPenId||!p[r+3].pPenId)r=!1;else{var B=p[r+1].pPenId;(B=this.j.get(B))&&B.Pf&&2===B.Pf?(B=p[r+2].pPenId,B=this.j.get(B),!B||!B.Pf||3>B.Pf?r=!1:(B=p[r+3].pPenId,r=(B=this.j.get(B))&&
B.Pf&&2===B.Pf?!0:!1)):r=!1}if(r){x=p[l+1].utf8;r=p[l+3].utf8;B=p[l+2].utf8;var E=this.j.get(p[l+2].pPenId);w=veb(w,x,B,r,E);m=new P4(d,e,n,f,w,m,z);l+=3}else m=new P4(d+x,e-x,n,h.id,w,m,z||q);m&&(a.push(m),h.j.push(m))}m=!0}}}b=a}else b=[];return b};Ceb.prototype.clear=function(){this.B=this.time=this.mode=0;this.j=[];this.reset()};
Ceb.prototype.reset=function(){this.mode=0;this.C.reset(0);this.D.reset(1)};
var Deb=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];a5.prototype.set=function(a){this.type=a};
a5.prototype.get=function(){return this.type};
b5.prototype.clear=function(){this.state=0};
b5.prototype.update=function(){this.state=2===this.state?1:0};
b5.prototype.Ee=function(){return 0!==this.state};
b5.prototype.matches=function(a,b){return this.Ee()&&a===this.ou&&b===this.Br};
Ieb.prototype.reset=function(){this.timestamp=this.j=0};
c5.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
c5.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
c5.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.u=this.row=1};
var Jeb=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Keb=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Leb=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Meb=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Qeb.prototype.reset=function(a,b){this.D=b;this.style.set(2);this.u=this.I;this.C=this.J;this.j=this.u;var c=(a<<2)+(b<<1);this.I.reset(c);this.J.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
Beb.prototype.reset=function(a){this.D=a;this.u.clear();this.C=this.B;this.B.reset(a,0);this.I.reset(a,1)};Ueb.prototype.C=function(){};g.v(h5,Ueb);h5.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+R4++;c=c/1E3-this.I;d=d/1E3-this.I;a=new Q4(c,d-c,5,f,{textAlign:0,yl:0,Lj:2.5*b,An:5.33*a});e=new P4(c,d-c,5,f,e);this.u.push(a);this.u.push(e)}};
g.v(k5,S4);k5.prototype.u=function(a){a=new h5(a,a.byteLength,this.B);if(Veb(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.B=j5(a)*(1E3/45):1===a.version&&(a.B=4294967296*j5(a)+j5(a)),a.D=i5(a);0<a.D;a.D--){var b=i5(a),c=i5(a),d=i5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.B,type:this.track,mS:c,nS:d,order:b.j.length}))}Heb(this.j,a);return a.u}return[]};
k5.prototype.reset=function(){this.j.clear()};g.v(l5,S4);
l5.prototype.u=function(a,b){var c=[];a=a.split(xfb);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!yfb.test(e)){var h=zfb.exec(e);if(h&&4<=h.length){var l=Yeb(h[1]),m=Yeb(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var r=null,w="";n=g.t(n);for(var x=n.next();!x.done;x=n.next())if(x=x.value.split(":"),2===x.length){var z=x[1];switch(x[0]){case "line":x=z.split(",");x[0].endsWith("%")&&(p=x[0],h.An=Number.parseInt(p,10),2===x.length&&(q=x[1].trim()));break;case "position":x=
z.split(",");r=x[0];h.Lj=Number.parseInt(r,10);2===x.length&&(w=x[1].trim());break;case "align":switch(z){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!r)switch(h.textAlign){case 0:h.Lj=0;break;case 1:h.Lj=100;break;case 2:h.Lj=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(w){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.yl=q}e=e.substring(zfb.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");w=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=Zeb(l,m,5,w),m=new P4(l,m,5,f.id,h,!1,g.Rc(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(Afb),1===q.length?(h=5,w=Zeb(l,m,h,w)):(p=h=6,w=Object.assign({Fr:32},w),w=new Q4(l,m,p,"_"+R4++,w)),c.push(w),p=l,r=0;r<q.length;r++)n=q[r],0===r%2?(x=g.D7a("<html>"+n+"</html>"),x.getElementsByTagName("parsererror").length?
(z=x.createElement("span"),z.appendChild(x.createTextNode(n))):z=x.firstChild,Xeb(this,p,m-(p-l),h,w,0<r,z,e,c)):p=Yeb(n)+f}zfb.lastIndex=0}}return c};
var yfb=/^NOTE/,xfb=/(?:\r\n|\r|\n){2,}/,zfb=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Afb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.QV.Ay(l5,{u:"wvppt"});g.v(m5,g.C);m5.prototype.clear=function(){this.parser&&this.parser.dispose();this.parser=null};
m5.prototype.reset=function(){this.parser&&this.parser.reset()};
m5.prototype.ra=function(){g.C.prototype.ra.call(this);this.clear()};var v5={windowColor:"#080808",windowOpacity:0,textAlign:2,yl:7,Lj:50,An:100,isDefault:!0,De:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.v(n5,g.hS);g.k=n5.prototype;g.k.ra=function(){if(this.C||this.oa){var a=this.F.ye();a&&!a.isDisposed()&&a.Hx()}else ufb(this,!1);g.hS.prototype.ra.call(this)};
g.k.Yv=function(){if(this.Za)return this.C||this.oa;var a=Rdb(this.player.getAudioTrack(),g.MI(this.Z));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?o5(this):kfb(this)||o5(this)?!0:lfb(this)};
g.k.load=function(){var a=this;g.hS.prototype.load.call(this);this.J=this.player.getAudioTrack();this.u?this.j&&(this.fb.clear(),this.C?pfb(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.Ns(this.j,"json3",function(b,c,d,e){if(b){a.u.WN()&&(a.Fa=[],a.F.Gf("captions"),g.po(a.Ja),a.fb.reset());b=efb(a.fb,b,c,d,e);a.player.Be(b,void 0,a.jb);if(!(!a.Aa||a.oa||r5(a)||g.CI(a.Z)||g.vI(a.Z)||g.wI(a.Z)||"shortspage"===a.Z.Fa||a.player.isInline())){g.to(a.Ma);b=ueb({yl:0,Lj:5,An:5,Jq:2,textAlign:0,
oi:0,lang:"ru"});a.Ra=[b];d=["\u0414\u043b\u044f \u043d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u043d\u0430\u0436\u043c\u0438\u0442\u0435 \u043d\u0430 \u0437\u043d\u0430\u0447\u043e\u043a ",""];a.kb||(e=new g.ZN(g.rO()),g.D(a,e),a.kb=e.element);e=b.end-b.start;var f=g.hJ(a.j);f&&a.Ra.push(new P4(b.start,e,0,b.id,f));a.Ra.push(new P4(b.start,e,0,b.id,d[0]),new P4(b.start,e,0,b.id,a.kb,!0),new P4(b.start,e,0,b.id,d[1],!0));a.player.Be(a.Ra);g.ro(a.Ma)}!a.Aa||a.oa||r5(a)||(g.MI(a.Z)?t5(a,!0):
u5(a,!0),a.J&&(a.J.C=a.j),a.player.Yq());var h;null==(h=a.F.Nc())||h.xa("cc",{kind:c.kind});a.Aa=!1}}),this.C||this.oa||r5(this)||this.player.Na("captionschanged",g.iJ(this.j))):(this.u=mfb(this),g.D(this,this.u),this.u.Oy(function(){ofb(a)}))};
g.k.unload=function(){this.C&&this.j?pfb(this,!1):(this.Ma&&g.to(this.Ma),this.player.Gf("captions"),this.Fa=[],this.u&&this.u.Xq(),this.fb.clear(),this.T&&this.player.Be(this.T),this.xP());g.hS.prototype.unload.call(this);this.player.Yq();this.player.Na("captionschanged",{})};
g.k.create=function(){this.Yv()&&this.load();var a;a:{var b,c,d;if(this.Z.K("suggest_caption_correction_menu_item")&&this.Z.K("web_player_nitrate_promo_tooltip")&&(null==(b=this.videoData.getPlayerResponse())?0:null==(c=b.captions)?0:null==(d=c.playerCaptionsTracklistRenderer)?0:d.openTranscriptCommand)){var e,f;if(b=null==(a=this.videoData.getPlayerResponse())?void 0:null==(e=a.captions)?void 0:null==(f=e.playerCaptionsTracklistRenderer)?void 0:f.captionTracks)for(a=g.t(b),e=a.next();!e.done;e=a.next())if(e=
e.value,"asr"===e.kind&&"en"===e.languageCode){a=!0;break a}}a=!1}a&&this.F.ma("showpromotooltip",this.I.element)};
g.k.G7=function(){for(var a=this.F.ye().xb().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;for(var d=g.iS(this.u.j,!0),e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.j:null)!==b&&s5(this,b,!0)};
g.k.D9=function(){!this.j&&this.C||this.unload()};
g.k.onCueRangeEnter=function(a){this.Fa.push(a);g.po(this.Ja)};
g.k.onCueRangeExit=function(a){g.qb(this.Fa,a);this.u instanceof K4&&this.u.I&&this.player.Ch([a]);g.po(this.Ja)};
g.k.getCaptionWindowContainerId=function(){return this.I.element.id};
g.k.z8=function(){tfb(this,this.Ra);this.Ra=null};
g.k.uP=function(){var a=this;if(!this.Tb||!this.C){this.Ja.stop();g.gba(this.Ta);this.Fa.sort(g.lC);var b=this.Fa;if(this.T){var c=g.Km(b,function(f){return-1===this.T.indexOf(f)},this);
c.length&&(b=c)}b=g.t(b);for(c=b.next();!c.done;c=b.next())rfb(this,c.value);b={};c=g.t(Object.entries(this.ea));for(var d=c.next();!d.done;b={Ot:b.Ot,gm:b.gm},d=c.next()){var e=g.t(d.value);d=e.next().value;e=e.next().value;b.Ot=d;b.gm=e;this.Ta[b.Ot]?(b.gm.element.parentNode||(b.gm instanceof O4||b.gm instanceof N4||g.Ic(this.ea,function(f){return function(h,l){l!==f.Ot&&h.u.params.yl===f.gm.u.params.yl&&h.u.params.Lj===f.gm.u.params.Lj&&h.u.params.An===f.gm.u.params.An&&(h.dispose(),delete a.ea[l]);
return l===f.Ot}}(b),this),this.I.element.appendChild(b.gm.element)),b.gm.Iz(this.Ta[b.Ot])):(b.gm.dispose(),delete this.ea[b.Ot])}}};
g.k.D8=function(){ifb(this,{},!0);this.player.Na("captionssettingschanged")};
g.k.q3=function(){var a=v5.De;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:v5.windowColor,windowOpacity:v5.windowOpacity};var b=Zdb()||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.kY=function(a,b){var c={};Object.assign(c,Zdb());Object.assign(c,a);ifb(this,c,b);this.player.Na("captionssettingschanged")};
g.k.xP=function(){!this.C&&this.loaded&&(g.Fc(this.ea,function(a,b){a.dispose();delete this.ea[b]},this),this.uP())};
g.k.qh=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.ie(b,-2,4);this.kY({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&s5(this,this.j,!0);break;case "stickyLoading":void 0!==b&&this.Z.I&&(g.MI(this.Z)?t5(this,!!b):u5(this,!!b));break;case "track":if(!this.u)return{};if(b){if(this.C)break;if(!g.Ja(b))break;if(g.Rc(b)){s5(this,null,!0);break}a=g.iS(this.u.j,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||
this.Z.K("html5_enable_caption_changes_for_mosaic")&&(e.captionId||"")!==(b.captionId||""))||(c=b.translationLanguage?Tdb(e,b.translationLanguage):e)}this.iI(b.position);!c||c===this.j&&this.loaded||(a=g.fH(),b=g.jJ(c),a.length&&b===a[a.length-1]||(a.push(b),g.qB("yt-player-caption-language-preferences",a)),(a=Sdb(this.Z))&&!this.F.isInline()&&g.qB("yt-player-caption-sticky-language",b,86400*a),s5(this,c,!0))}else return this.loaded&&this.j&&!r5(this)?g.iJ(this.j):{};return"";case "tracklist":return this.u?
g.vh(g.iS(this.u.j,!(!b||!b.includeAsr)),function(f){return g.iJ(f)}):[];
case "translationLanguages":return this.u?this.u.C.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.C||void 0===b||ufb(this,!!b);break;case "sampleSubtitlesCustomized":this.C||ufb(this,!!b,b);break;case "recommendedTranslationLanguages":return g.fH()}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Z.I&&a.push("stickyLoading");return a};
g.k.aq=function(){var a=this.j;if(a){var b=a.vssId;a.translationLanguage&&b&&(b="t"+b+"."+g.jJ(a));return{cc:b}}return{}};
g.k.q9=function(){this.isSubtitlesOn()?(g.MI(this.Z)?t5(this,!1):u5(this,!1),this.unload(),o5(this,!0)&&s5(this,p5(this),!1)):this.OX()};
g.k.OX=function(){this.isSubtitlesOn()||s5(this,r5(this)||!this.j?q5(this,!0):this.j,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.j&&!r5(this)};
g.k.x5=function(){var a=r5(this);o5(this,a)?s5(this,this.player.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.Yv()&&(a?s5(this,q5(this),!1):this.load()))};
g.k.iI=function(a){a&&(this.Y={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.I.element.style.top=100*this.Y.top+"%",this.I.element.style.left=100*this.Y.left+"%",this.I.element.style.width=100*this.Y.width+"%",this.I.element.style.height=100*this.Y.height+"%",this.Z.K("html5_enable_caption_changes_for_mosaic")&&(this.I.element.style.position="absolute",a=sfb(this)))&&(this.I.element.style.width=a.width+"px",this.I.element.style.height=a.height+
"px")};
g.k.j6=function(){var a=this.F.ye();a&&!a.isDisposed()&&a.Hx();this.F.isFullscreen()?(this.C=this.Za=!0,this.loaded&&ofb(this)):(this.Za="3"===this.Z.controlsType,this.C=hfb(this));s5(this,this.j)};
g.k.RI=function(){var a,b,c,d=null==(a=this.videoData.getPlayerResponse())?void 0:null==(b=a.captions)?void 0:null==(c=b.playerCaptionsTracklistRenderer)?void 0:c.openTranscriptCommand;d&&this.player.Na("innertubeCommand",d)};
g.QV.Ay(n5,{uP:"smucd"});g.gS("captions",n5);})(_yt_player);
