(function(g){var window=this;'use strict';var Tfb=function(a,b){a.Na("onAutonavCoundownStarted",b)},E5=function(a,b,c){g.Co(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.hg(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.OJ&&(b.lengthText?(e=b.lengthText||null,f=b.hv||null):b.lengthSeconds&&(e=g.eP(b.lengthSeconds),f=g.eP(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.MJ(d).type;var l=b instanceof g.OJ?b.isLivePlayback:null,m=b instanceof g.OJ?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,r=[],w=[];n&&r.push(n);p&&(r.push(p),w.push(p));q&&w.push(q);c={title:b.title,author:n,author_and_views:r.join(" \u2022 "),aria_label:b.ariaLabel||
g.sM("\u041f\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u0442\u044c $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Jo(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:w.join(" \u2022 "),autoplayAlternativeHeader:b.Ar};b instanceof g.NJ&&(c.playlist_length=b.playlistLength);a.update(c)},F5=function(a){var b=a.V(),c=b.C;
g.T.call(this,{G:"a",N:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:c?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{G:"div",Ia:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},W:[{G:"div",X:{"aria-label":"{{timestamp}}"},Ia:["ytp-autonav-timestamp"],qa:"{{duration}}"},{G:"div",Ia:["ytp-autonav-live-stamp"],qa:"\u0412 \u044d\u0444\u0438\u0440\u0435"},
{G:"div",Ia:["ytp-autonav-upcoming-stamp"],qa:"\u0421\u043a\u043e\u0440\u043e \u0432 \u044d\u0444\u0438\u0440\u0435"},{G:"div",N:"ytp-autonav-list-overlay",W:[{G:"div",N:"ytp-autonav-mix-text",qa:"\u041c\u0438\u043a\u0441"},{G:"div",N:"ytp-autonav-mix-icon"}]}]},{G:"div",Ia:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],qa:"{{title}}"},{G:"div",Ia:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],qa:"{{author}}"},{G:"div",Ia:["ytp-autonav-endscreen-upnext-author",
"ytp-autonav-view-and-date-card"],qa:"{{views_and_publish_time}}"}]});this.F=a;this.suggestion=null;this.j=c;this.Qa("click",this.onClick);this.Qa("keypress",this.onKeyPress)},G5=function(a,b){b=void 0===b?!1:b;
g.T.call(this,{G:"div",N:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.I=b;this.D=void 0;this.B=0;this.container=new g.T({G:"div",N:"ytp-autonav-endscreen-countdown-container"});g.D(this,this.container);this.container.Ea(this.element);b=a.V();var d=b.C;this.F=a;this.suggestion=null;this.onVideoDataChange("newdata",this.F.getVideoData());this.S(a,"videodatachange",this.onVideoDataChange);var e=["ytp-autonav-endscreen-upnext-thumbnail"];b.K("web_rounded_thumbnails")&&e.push("rounded-thumbnail");
this.j=new g.T({G:"div",N:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},W:[{G:"div",N:"ytp-autonav-endscreen-upnext-header"},{G:"div",N:"ytp-autonav-endscreen-upnext-alternative-header",qa:"{{autoplayAlternativeHeader}}"},{G:"a",N:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:d?b.Y:""},W:[{G:"div",Ia:e,X:{style:"{{background}}"},W:[{G:"div",
X:{"aria-label":"{{timestamp}}"},Ia:["ytp-autonav-timestamp"],qa:"{{duration}}"},{G:"div",Ia:["ytp-autonav-live-stamp"],qa:"\u0412 \u044d\u0444\u0438\u0440\u0435"},{G:"div",Ia:["ytp-autonav-upcoming-stamp"],qa:"\u0421\u043a\u043e\u0440\u043e \u0432 \u044d\u0444\u0438\u0440\u0435"}]},{G:"div",N:"ytp-autonav-endscreen-video-info",W:[{G:"div",N:"ytp-autonav-endscreen-premium-badge"},{G:"div",N:"ytp-autonav-endscreen-upnext-title",qa:"{{title}}"},{G:"div",N:"ytp-autonav-endscreen-upnext-author",qa:"{{author}}"},
{G:"div",N:"ytp-autonav-view-and-date",qa:"{{views_and_publish_time}}"},{G:"div",N:"ytp-autonav-author-and-view",qa:"{{author_and_views}}"}]}]}]});g.D(this,this.j);this.j.Ea(this.container.element);d||this.S(this.j.Da("ytp-autonav-endscreen-link-container"),"click",this.jQ);this.F.sb(this.container.element,this,115127);this.F.sb(this.j.Da("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.T({G:"div",N:"ytp-autonav-overlay"});g.D(this,this.overlay);this.overlay.Ea(this.container.element);
this.u=new g.T({G:"div",N:"ytp-autonav-endscreen-button-container"});g.D(this,this.u);this.u.Ea(this.container.element);this.cancelButton=new g.T({G:"button",Ia:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.K("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{"aria-label":"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u0430\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435"},
qa:"\u041e\u0442\u043c\u0435\u043d\u0430"});g.D(this,this.cancelButton);this.cancelButton.Ea(this.u.element);this.cancelButton.Qa("click",this.CZ,this);this.F.sb(this.cancelButton.element,this,115129);this.playButton=new g.T({G:"a",Ia:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",b.K("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],X:{href:"{{url}}",role:"button","aria-label":"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 \u0432\u0438\u0434\u0435\u043e"},
qa:"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438"});g.D(this,this.playButton);this.playButton.Ea(this.u.element);this.playButton.Qa("click",this.jQ,this);this.F.sb(this.playButton.element,this,115130);this.C=new g.qo(function(){Ufb(c)},500);
g.D(this,this.C);this.iQ();this.S(a,"autonavvisibility",this.iQ);this.F.K("web_autonav_color_transition")&&(this.S(a,"autonavchange",this.BZ),this.S(a,"onAutonavCoundownStarted",this.y5))},H5=function(a){var b=a.F.zk(!0,a.F.isFullscreen());
g.Co(a.container.element,"ytp-autonav-endscreen-small-mode",a.jh(b));g.Co(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.SH);g.Co(a.F.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.F.Nf());g.Co(a.F.getRootNode(),"countdown-running",a.Fk());g.Co(a.container.element,"ytp-player-content",a.F.Nf());g.Jl(a.overlay.element,{width:b.width+"px"});if(!a.Fk()){a.F.Nf()?Vfb(a,Math.round(Wfb(a)/1E3)):Vfb(a);b=!!a.suggestion&&!!a.suggestion.Ar;var c=a.F.Nf()||!b;
g.Co(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.Co(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.bO(a.u,a.F.Nf());g.Co(a.element,"ytp-enable-w2w-color-transitions",Xfb(a))}},Ufb=function(a){var b=Wfb(a),c=Math,d=c.min;
var e=a.B?Date.now()-a.B:0;c=d.call(c,e,b);Vfb(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Fk()?a.select(!0):a.Fk()&&a.C.start()},Wfb=function(a){if(a.F.isFullscreen()){var b;
a=null==(b=a.F.getVideoData())?void 0:b.xI;return-1===a||void 0===a?8E3:a}return 0<=a.F.Tr()?a.F.Tr():g.rH(a.F.V().experiments,"autoplay_time")||1E4},Xfb=function(a){var b;
return!(null==(b=a.F.getVideoData())||!b.watchToWatchTransitionRenderer)},Vfb=function(a,b){b=void 0===b?-1:b;
a=a.j.Da("ytp-autonav-endscreen-upnext-header");g.Ve(a);if(0<=b){b=String(b);var c="\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.Te("\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".slice(0,
d)));var e=g.Ne("span");g.wo(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.$e(e,b);a.appendChild(e);a.appendChild(g.Te("\u0412\u0438\u0434\u0435\u043e \u043d\u0430\u0447\u043d\u0435\u0442\u0441\u044f \u0447\u0435\u0440\u0435\u0437 $SECONDS".slice(d+c.length)));return}}g.$e(a,"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435")},I5=function(a,b){g.T.call(this,{G:"div",
Ia:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},J5=function(a){g.T.call(this,{G:"div",
Ia:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},W:[{G:"div",N:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{G:"span",N:"ytp-upnext-top",W:[{G:"span",N:"ytp-upnext-header",qa:"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},{G:"span",N:"ytp-upnext-title",qa:"{{title}}"},{G:"span",N:"ytp-upnext-author",qa:"{{author}}"}]},{G:"a",N:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0441\u0442\u0438 \u0441\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 \u0432\u0438\u0434\u0435\u043e"},
W:[{G:"svg",X:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},W:[{G:"circle",N:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{G:"circle",N:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{G:"path",N:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{G:"span",N:"ytp-upnext-bottom",
W:[{G:"span",N:"ytp-upnext-cancel"},{G:"span",N:"ytp-upnext-paused",qa:"\u0410\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043f\u0440\u0438\u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e."}]}]});this.api=a;this.cancelButton=null;this.D=this.Da("ytp-svg-autoplay-ring");this.B=this.notification=this.j=this.suggestion=null;this.C=new g.qo(this.bF,5E3,this);this.u=0;var b=this.Da("ytp-upnext-cancel");this.cancelButton=
new g.T({G:"button",Ia:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u0430\u0432\u0442\u043e\u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435"},qa:"\u041e\u0442\u043c\u0435\u043d\u0430"});g.D(this,this.cancelButton);this.cancelButton.Qa("click",this.DZ,this);this.cancelButton.Ea(b);this.cancelButton&&this.api.sb(this.cancelButton.element,this,115129);g.D(this,this.C);this.api.sb(this.element,
this,18788);b=this.Da("ytp-upnext-autoplay-icon");this.S(b,"click",this.EZ);this.api.sb(b,this,115130);this.kQ();this.S(a,"autonavvisibility",this.kQ);this.S(a,"mdxnowautoplaying",this.l6);this.S(a,"mdxautoplaycanceled",this.m6);g.Co(this.element,"ytp-upnext-mobile",this.api.V().u)},Yfb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.xI;return-1===a||void 0===a?8E3:a}return 0<=a.api.Tr()?a.api.Tr():g.rH(a.api.V().experiments,"autoplay_time")||1E4},Zfb=function(a,b){b=Yfb(a,b);
var c=Math,d=c.min;var e=(0,g.M)()-a.u;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.D.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Fk()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Fk()&&a.j.start()},K5=function(a){I5.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.T({G:"div",N:"ytp-suggestion-panel",W:[{G:"div",Ia:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],qa:"\u041f\u043e\u043a\u0430\u0437\u0430\u0442\u044c \u0434\u0440\u0443\u0433\u0438\u0435 \u0432\u0438\u0434\u0435\u043e"}]});this.J=new g.T({G:"div",N:"ytp-suggestions-container"});this.videos=[];this.B=null;this.D=this.I=!1;this.u=new G5(this.player);g.D(this,this.u);this.u.Ea(this.element);a.getVideoData().vf?this.j=this.u:
(this.j=new J5(a),g.oR(this.player,this.j.element,4),g.D(this,this.j));this.overlay=new g.T({G:"div",N:"ytp-autonav-overlay-cancelled-state"});g.D(this,this.overlay);this.overlay.Ea(this.element);this.C=new g.nG(this);g.D(this,this.C);g.D(this,this.table);this.table.Ea(this.element);this.table.show();g.D(this,this.J);this.J.Ea(this.table.element);this.hide()},L5=function(a){var b=a.Nf();
b!==a.D&&(a.D=b,a.player.ma("autonavvisibility"),a.D?(a.u!==a.j&&a.u.hide(),a.table.hide()):(a.u!==a.j&&a.u.show(),a.table.show()))},M5=function(a,b){g.T.call(this,{G:"button",
Ia:["ytp-watch-on-youtube-button","ytp-button"],qa:"{{content}}"});this.F=a;this.buttonType=this.buttonType=b;b=this.F.getVideoData();if(a.K("embeds_enable_server_driven_watch_again_on_youtube")){var c,d;if(c=(a=null==(c=b.jd)?void 0:null==(d=c.playerOverlays)?void 0:d.playerOverlayRenderer)&&g.K(a.watchOnYoutubeButton,g.XKa))this.j=c}if(this.j)this.update({content:this.j.title}),this.F.Bg(this.element,this),this.F.Lg(this.element,this.j.trackingParams||null);else{switch(this.buttonType){case 1:c=
"\u041f\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u0442\u044c \u0441\u043d\u043e\u0432\u0430 \u043d\u0430 YouTube";d=156915;break;case 2:c="\u041f\u0440\u043e\u0434\u043e\u043b\u0436\u0438\u0442\u044c \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 \u043d\u0430 YouTube";d=156942;break;default:c="\u041f\u0440\u043e\u0434\u043e\u043b\u0436\u0438\u0442\u044c \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 \u043d\u0430 YouTube",d=156942}this.update({content:c});this.F.sb(this.element,this,d)}2===this.buttonType&&
g.yo(this.element,"ytp-continue-watching-button");this.Qa("click",this.onClick);g.bO(this,!0)},N5=function(a,b){I5.call(this,a,"embeds-lite-endscreen");
this.F=a;this.j=b;this.F.sb(this.element,this,156943);this.watchButton=new M5(a,2);g.D(this,this.watchButton);this.watchButton.Ea(this.element);this.hide()},$fb=function(a){I5.call(this,a,"subscribecard-endscreen");
this.j=new g.T({G:"div",N:"ytp-subscribe-card",W:[{G:"img",N:"ytp-author-image",X:{src:"{{profilePicture}}"}},{G:"div",N:"ytp-subscribe-card-right",W:[{G:"div",N:"ytp-author-name",qa:"{{author}}"},{G:"div",N:"html5-subscribe-button-container"}]}]});g.D(this,this.j);this.j.Ea(this.element);var b=a.getVideoData();this.subscribeButton=new g.lT("\u041f\u043e\u0434\u043f\u0438\u0441\u0430\u0442\u044c\u0441\u044f",null,"\u041e\u0442\u043c\u0435\u043d\u0438\u0442\u044c \u043f\u043e\u0434\u043f\u0438\u0441\u043a\u0443",
null,!0,!1,b.dk,b.subscribed,"trailer-endscreen",null,null,a);g.D(this,this.subscribeButton);this.subscribeButton.Ea(this.j.Da("html5-subscribe-button-container"));this.S(a,"videodatachange",this.La);this.La();this.hide()},O5=function(a){var b=a.V(),c=g.qG||g.mI?{style:"will-change: opacity"}:void 0,d=b.C,e=["ytp-videowall-still"];
b.u&&e.push("ytp-videowall-show-text");g.T.call(this,{G:"a",Ia:e,X:{href:"{{url}}",target:d?b.Y:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},W:[{G:"div",N:"ytp-videowall-still-image",X:{style:"{{background}}"}},{G:"span",N:"ytp-videowall-still-info",X:{"aria-hidden":"true"},W:[{G:"span",N:"ytp-videowall-still-info-bg",W:[{G:"span",N:"ytp-videowall-still-info-content",X:c,W:[{G:"span",N:"ytp-videowall-still-info-title",qa:"{{title}}"},
{G:"span",N:"ytp-videowall-still-info-author",qa:"{{author_and_views}}"},{G:"span",N:"ytp-videowall-still-info-live",qa:"\u0412 \u044d\u0444\u0438\u0440\u0435"},{G:"span",N:"ytp-videowall-still-info-duration",qa:"{{duration}}"}]}]}]},{G:"span",Ia:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},W:[{G:"span",N:"ytp-videowall-still-listlabel-icon"},"\u041f\u043b\u0435\u0439\u043b\u0438\u0441\u0442",{G:"span",N:"ytp-videowall-still-listlabel-length",
W:[" (",{G:"span",qa:"{{playlist_length}}"},")"]}]},{G:"span",Ia:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},W:[{G:"span",N:"ytp-videowall-still-listlabel-mix-icon"},"\u041c\u0438\u043a\u0441",{G:"span",N:"ytp-videowall-still-listlabel-length",qa:" (50+)"}]}]});this.suggestion=null;this.u=d;this.api=a;this.j=new g.nG(this);g.D(this,this.j);this.Qa("click",this.onClick);this.Qa("keypress",this.onKeyPress);this.j.S(a,"videodatachange",this.onVideoDataChange);
a.Bg(this.element,this);this.onVideoDataChange()},P5=function(a){I5.call(this,a,"videowall-endscreen");
var b=this;this.F=a;this.B=0;this.stills=[];this.C=this.videoData=null;this.D=this.J=!1;this.T=null;this.u=new g.nG(this);g.D(this,this.u);this.Y=a.K("web_rounded_thumbnails");this.I=new g.qo(function(){g.yo(b.element,"ytp-show-tiles")},0);
g.D(this,this.I);var c=new g.T({G:"button",Ia:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"\u041d\u0430\u0437\u0430\u0434"},W:[g.hO()]});g.D(this,c);c.Ea(this.element);c.Qa("click",this.IZ,this);this.table=new g.ZN({G:"div",N:"ytp-endscreen-content"});g.D(this,this.table);this.table.Ea(this.element);c=new g.T({G:"button",Ia:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435"},W:[g.iO()]});g.D(this,c);c.Ea(this.element);c.Qa("click",
this.HZ,this);a.getVideoData().vf?this.j=new G5(a,!0):this.j=new J5(a);g.D(this,this.j);g.oR(this.player,this.j.element,4);a.sb(this.element,this,158789);this.hide()},Q5=function(a){return g.pR(a.player)&&a.QA()&&!a.C},R5=function(a){var b=a.Nf();
b!==a.J&&(a.J=b,a.player.ma("autonavvisibility"))},S5=function(a){I5.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new M5(a,1);g.D(this,this.watchButton);this.watchButton.Ea(this.element);g.E7a(a)&&(this.j=new g.E2(a,g.XQ(a)),g.D(this,this.j),this.u=new g.T({G:"div",Ia:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},W:[this.j]}),g.D(this,this.u),this.j.Ea(this.u.element),this.u.Ea(this.element));a.sb(this.element,this,156914);this.hide()},dgb=function(a){g.hS.call(this,a);
var b=this;this.endScreen=null;this.u=this.j=this.B=this.C=!1;this.listeners=new g.nG(this);g.D(this,this.listeners);var c=a.V(),d=a.getVideoData();d=d&&0!==d.endSeconds;if(g.Ex(g.FI(c))&&d&&!g.lR(a))this.u=!0,this.endScreen=new N5(a,g.XQ(a));else{var e;(c.K("shorts_mode_to_player_api")?a.Sb():null==(e=g.XQ(a))?0:e.Sb())?this.endScreen=new S5(a):agb(a)?(this.C=!0,bgb(this),this.j?this.endScreen=new K5(a):this.endScreen=new P5(a)):c.Zg?this.endScreen=new $fb(a):this.endScreen=new I5(a)}g.D(this,this.endScreen);
g.oR(a,this.endScreen.element,4);cgb(this);this.listeners.S(a,"videodatachange",this.onVideoDataChange,this);this.listeners.S(a,g.mC("endscreen"),function(f){b.onCueRangeEnter(f)});
this.listeners.S(a,g.nC("endscreen"),function(f){b.onCueRangeExit(f)})},bgb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.fl&&a.B===b.vf)return!1;a.j=b.fl;a.B=b.vf;return!0},agb=function(a){a=a.V();
return a.Bd&&!a.Zg},cgb=function(a){a.player.Gf("endscreen");
var b=a.player.getVideoData();b=new g.kC(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.kC(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.Be([b,c])};
g.FV.prototype.Ez=g.ca(36,function(a){this.MN!==a&&(this.MN=a,this.bl())});
g.jU.prototype.Qq=g.ca(35,function(a){this.u!==a&&(this.u=a,this.La())});
g.FV.prototype.Qq=g.ca(34,function(a){this.shareButton&&this.shareButton.Qq(a)});
g.ZT.prototype.Pq=g.ca(33,function(a){this.u!==a&&(this.u=a,this.La())});
g.FV.prototype.Pq=g.ca(32,function(a){this.overflowButton&&this.overflowButton.Pq(a)});
g.YS.prototype.GD=g.ca(31,function(a){this.NN!==a&&(this.NN=a,this.xp())});
g.hR.prototype.Tr=g.ca(5,function(){return this.app.Tr()});
g.hZ.prototype.Tr=g.ca(4,function(){return this.getVideoData().tR});g.v(F5,g.T);F5.prototype.select=function(){this.F.Hn(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.jB||void 0)&&this.F.ob(this.element)};
F5.prototype.onClick=function(a){g.JS(a,this.F,this.j,this.suggestion.sessionData||void 0)&&this.select()};
F5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.gA(a)||(this.select(),g.fA(a))}};g.v(G5,g.T);g.k=G5.prototype;g.k.pE=function(a){this.suggestion!==a&&(this.suggestion=a,E5(this.j,a),this.playButton.updateValue("url",this.suggestion.Jo()),H5(this))};
g.k.Fk=function(){return 0<this.B};
g.k.Mz=function(){this.Fk()||(this.B=Date.now(),Ufb(this),Tfb(this.F,Wfb(this)),g.Co(this.F.getRootNode(),"countdown-running",this.Fk()))};
g.k.Gv=function(){this.Uq();Ufb(this);var a=this.j.Da("ytp-autonav-endscreen-upnext-header");a&&g.$e(a,"\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435")};
g.k.Uq=function(){this.Fk()&&(this.C.stop(),this.B=0)};
g.k.select=function(a){this.F.nextVideo(!1,void 0===a?!1:a);this.Uq()};
g.k.jQ=function(a){g.JS(a,this.F)&&(a.currentTarget===this.playButton.element?this.F.ob(this.playButton.element):a.currentTarget===this.j.Da("ytp-autonav-endscreen-link-container")&&(a=this.j.Da("ytp-autonav-endscreen-link-container"),this.F.Ua(a,!0),this.F.ob(a)),this.select())};
g.k.CZ=function(){this.F.ob(this.cancelButton.element);g.jR(this.F,!0);this.D&&this.F.Na("innertubeCommand",this.D)};
g.k.onVideoDataChange=function(a,b){var c;this.D=null==(c=b.H0)?void 0:c.command};
g.k.y5=function(a){if(Xfb(this)){var b=this.F.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.pP(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.pP(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.pP(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.pP(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.pP(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.pP(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.Co(this.element,"ytp-w2w-animate",!0)}};
g.k.BZ=function(a){this.F.K("web_autonav_color_transition")&&2!==a&&g.Co(this.element,"ytp-w2w-animate",!1)};
g.k.iQ=function(){var a=this.F.Nf();this.I&&this.vb!==a&&g.bO(this,a);H5(this);this.F.Ua(this.container.element,a);this.F.Ua(this.cancelButton.element,a);this.F.Ua(this.j.Da("ytp-autonav-endscreen-link-container"),a);this.F.Ua(this.playButton.element,a)};
g.k.jh=function(a){return 400>a.width||459>a.height};g.v(I5,g.T);g.k=I5.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.QA=function(){return!1};
g.k.Nf=function(){return!1};
g.k.EU=function(){return!1};g.v(J5,g.T);g.k=J5.prototype;g.k.bF=function(){this.notification&&(this.C.stop(),this.Hc(this.B),this.B=null,this.notification.close(),this.notification=null)};
g.k.pE=function(a){this.suggestion=a;E5(this,a,"hqdefault.jpg")};
g.k.kQ=function(){g.bO(this,this.api.Nf());this.api.Ua(this.element,this.api.Nf());this.api.Ua(this.Da("ytp-upnext-autoplay-icon"),this.api.Nf());this.cancelButton&&this.api.Ua(this.cancelButton.element,this.api.Nf())};
g.k.u6=function(){window.focus();this.bF()};
g.k.Mz=function(a){var b=this;this.Fk()||(g.vA("a11y-announce","\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435 "+this.suggestion.title),this.u=(0,g.M)(),this.j=new g.qo(function(){Zfb(b,a)},25),Zfb(this,a),Tfb(this.api,Yfb(this,a)));
g.Ao(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.T.prototype.hide.call(this)};
g.k.Fk=function(){return!!this.j};
g.k.Gv=function(){this.Uq();this.u=(0,g.M)();Zfb(this);g.yo(this.element,"ytp-upnext-autoplay-paused")};
g.k.Uq=function(){this.Fk()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.V().K("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.bF(),this.notification=new Notification("\u0421\u043b\u0435\u0434\u0443\u044e\u0449\u0435\u0435",{body:this.suggestion.title,icon:this.suggestion.hg()}),this.B=this.S(this.notification,"click",this.u6),this.C.start())}this.Uq();this.api.nextVideo(!1,
a)};
g.k.EZ=function(a){!g.Ze(this.cancelButton.element,g.bA(a))&&g.JS(a,this.api)&&(this.api.Nf()&&this.api.ob(this.Da("ytp-upnext-autoplay-icon")),this.select())};
g.k.DZ=function(){this.api.Nf()&&this.cancelButton&&this.api.ob(this.cancelButton.element);g.jR(this.api,!0)};
g.k.l6=function(a){this.api.getPresentingPlayerType();this.show();this.Mz(a)};
g.k.m6=function(){this.api.getPresentingPlayerType();this.Uq();this.hide()};
g.k.ra=function(){this.Uq();this.bF();g.T.prototype.ra.call(this)};g.v(K5,I5);g.k=K5.prototype;g.k.create=function(){I5.prototype.create.call(this);this.C.S(this.player,"appresize",this.sA);this.C.S(this.player,"onVideoAreaChange",this.sA);this.C.S(this.player,"videodatachange",this.onVideoDataChange);this.C.S(this.player,"autonavchange",this.lQ);this.C.S(this.player,"autonavcancel",this.FZ);this.onVideoDataChange()};
g.k.show=function(){I5.prototype.show.call(this);(this.I||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.jR(this.player,!1);g.pR(this.player)&&this.QA()&&!this.B?(L5(this),2===this.videoData.autonavState?this.player.V().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Mz():3===this.videoData.autonavState&&this.j.Gv()):(g.jR(this.player,!0),L5(this));this.sA()};
g.k.hide=function(){I5.prototype.hide.call(this);this.j.Gv();L5(this)};
g.k.sA=function(){var a=this.player.zk(!0,this.player.isFullscreen());L5(this);H5(this.u);g.Co(this.element,"ytp-autonav-cancelled-small-mode",this.jh(a));g.Co(this.element,"ytp-autonav-cancelled-tiny-mode",this.lG(a));g.Co(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.Jl(this.overlay.element,{width:a.width+"px"});if(!this.D)for(a=0;a<this.videos.length;a++)g.Co(this.videos[a].element,"ytp-suggestion-card-with-margin",1===a%2)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.K("web_player_autonav_empty_suggestions_fix")){var b=g.yK(this.videoData);b&&(this.j.pE(b),this.j!==this.u&&this.u.pE(b))}if(a&&a.length)for(b=0;b<egb.length;++b){var c=egb[b];if(a&&a[c]){this.videos[b]=new F5(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,E5(d,c));g.D(this,this.videos[b]);this.videos[b].Ea(this.J.element)}}this.sA()}};
g.k.lQ=function(a){1===a?(this.I=!1,this.B=this.videoData.clientPlaybackNonce,this.j.Uq(),this.vb&&this.sA()):(this.I=!0,this.Nf()&&(2===a?this.j.Mz():3===a&&this.j.Gv()))};
g.k.FZ=function(a){a?this.lQ(1):(this.B=null,this.I=!1)};
g.k.QA=function(){return 1!==this.videoData.autonavState};
g.k.jh=function(a){return(910>a.width||459>a.height)&&!this.lG(a)&&!(400>=a.width||360>=a.height)};
g.k.lG=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Nf=function(){return this.vb&&g.pR(this.player)&&this.QA()&&!this.B};
var egb=[1,3,2,4];g.v(M5,g.T);g.k=M5.prototype;g.k.onClick=function(a){this.F.K("web_player_log_click_before_generating_ve_conversion_params")&&this.F.ob(this.element);this.j?this.F.Na("innertubeCommand",this.j.onTap):g.KS(this.getVideoUrl(),this.F,a);this.F.K("web_player_log_click_before_generating_ve_conversion_params")||this.F.ob(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.F.getVideoUrl(a,!1,!1,!0);var b=this.F.V();if(g.oI(b)||g.xI(b)){var c={};b.Aa&&g.oI(b)&&g.uQ(c,b.loaderUrl);g.oI(b)&&g.UQ(this.F,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.tQ(c,b);a=g.ri(a,c)}return a};
g.k.Ua=function(){this.F.Ua(this.element,this.vb&&this.Aa)};
g.k.show=function(){g.T.prototype.show.call(this);this.Ua()};
g.k.hide=function(){g.T.prototype.hide.call(this);this.Ua()};
g.k.kc=function(a){g.T.prototype.kc.call(this,a);this.Ua()};g.v(N5,I5);N5.prototype.show=function(){3!==this.player.getPlayerState()&&(I5.prototype.show.call(this),this.j.Ez(!0),this.j.Qq(!0),this.F.V().Yl||this.j.Pq(!0),this.F.Ua(this.element,!0),this.watchButton.kc(!0))};
N5.prototype.hide=function(){I5.prototype.hide.call(this);this.j.Ez(!1);this.j.Qq(!1);this.j.Pq(!1);this.F.Ua(this.element,!1);this.watchButton.kc(!1)};g.v($fb,I5);$fb.prototype.La=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.dk;var b=this.subscribeButton;a.subscribed?b.j():b.u()};g.v(O5,g.T);O5.prototype.select=function(){this.api.Hn(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.jB||void 0)&&this.api.ob(this.element)};
O5.prototype.onClick=function(a){g.JS(a,this.api,this.u,this.suggestion.sessionData||void 0)&&this.select()};
O5.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.gA(a)||(this.select(),g.fA(a))}};
O5.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.V();this.u=a.D?!1:b.C};g.v(P5,I5);g.k=P5.prototype;g.k.create=function(){I5.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Ep();this.u.S(this.player,"appresize",this.Ep);this.u.S(this.player,"onVideoAreaChange",this.Ep);this.u.S(this.player,"videodatachange",this.onVideoDataChange);this.u.S(this.player,"autonavchange",this.SI);this.u.S(this.player,"autonavcancel",this.GZ);a=this.videoData.autonavState;a!==this.T&&this.SI(a);this.u.S(this.element,"transitionend",this.H7)};
g.k.destroy=function(){g.mB(this.u);g.Za(this.stills);this.stills=[];I5.prototype.destroy.call(this);g.Ao(this.element,"ytp-show-tiles");this.I.stop();this.T=this.videoData.autonavState};
g.k.QA=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.vb;I5.prototype.show.call(this);g.Ao(this.element,"ytp-show-tiles");this.player.V().u?g.so(this.I):this.I.start();(this.D||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.jR(this.player,!1);Q5(this)?(R5(this),2===this.videoData.autonavState?this.player.V().K("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.j.select(!0):this.j.Mz():3===this.videoData.autonavState&&this.j.Gv()):(g.jR(this.player,!0),R5(this));a!==this.vb&&this.player.Ua(this.element,
!0)};
g.k.hide=function(){var a=this.vb;I5.prototype.hide.call(this);this.j.Gv();R5(this);a!==this.vb&&this.player.Ua(this.element,!1)};
g.k.H7=function(a){g.bA(a)===this.element&&this.Ep()};
g.k.Ep=function(){var a,b,c,d;var e=(null==(a=this.videoData)?0:null==(b=a.suggestions)?0:b.length)?null==(c=this.videoData)?void 0:c.suggestions:[null==(d=this.videoData)?void 0:g.yK(d)];if(e.length){g.yo(this.element,"ytp-endscreen-paginate");var f=this.F.zk(!0,this.F.isFullscreen());if(a=g.XQ(this.F))a=a.og()?48:32,f.width-=2*a;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;0<p&&(a<l||b<m);){var q=a/2,r=b/2,w=a<=l-2&&p>=r*n,x=b<=m-2&&p>=q*n;if((q+1)/r*d/h>h/(q/(r+1)*d)&&x)p-=q*n,b+=2;else if(w)p-=r*n,a+=2;else if(x)p-=q*n,b+=2;else break}d=!1;p>=3*n&&6>=c*n-p&&(4<=b||4<=a)&&(d=!0);n=96*a;p=54*b;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.Zl(f,n,p);g.Jl(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.pE(g.yK(this.videoData));this.j instanceof
G5&&H5(this.j);g.Co(this.element,"ytp-endscreen-takeover",Q5(this));R5(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,w=0,d&&l>=a-2&&m>=b-2?w=1:0===m%2&&0===l%2&&(2>m&&2>l?0===m&&0===l&&(w=2):w=2),q=g.je(q+this.B,c),0!==w){r=this.stills[h];r||(r=new O5(this.player),this.stills[h]=r,f.appendChild(r.element));x=Math.floor(p*m/b);var z=Math.floor(n*l/a),B=Math.floor(p*(m+w)/b)-x-4,E=Math.floor(n*(l+w)/a)-z-4;g.Pl(r.element,z,x);g.Zl(r.element,E,B);g.Jl(r.element,"transitionDelay",
(m+l)/20+"s");g.Co(r.element,"ytp-videowall-still-mini",1===w);g.Co(r.element,"ytp-videowall-still-large",2<w);this.Y&&(w=Math.max(E,B),g.Co(r.element,"ytp-videowall-still-round-large",256<=w),g.Co(r.element,"ytp-videowall-still-round-medium",96<w&&256>w),g.Co(r.element,"ytp-videowall-still-round-small",96>=w));q=e[q];r.suggestion!==q&&(r.suggestion=q,w=r.api.V(),x=g.xo(r.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",E5(r,q,x),g.oI(w)&&(x=q.Jo(),z={},w.Aa&&g.uQ(z,w.loaderUrl),
g.UQ(r.api,"addEmbedsConversionTrackingParams",[z]),x=g.ri(x,g.tQ(z,"emb_rel_end")),r.updateValue("url",x)),(q=(q=q.sessionData)&&q.itct)&&r.api.Lg(r.element,q));h++}f.ariaBusy="false";g.Co(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.Xe(a.element),g.Ya(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.B=0,this.videoData=a,this.Ep())};
g.k.HZ=function(){this.B+=this.stills.length;this.Ep()};
g.k.IZ=function(){this.B-=this.stills.length;this.Ep()};
g.k.EU=function(){return this.j.Fk()};
g.k.SI=function(a){1===a?(this.D=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Uq(),this.vb&&this.Ep()):(this.D=!0,this.vb&&Q5(this)&&(2===a?this.j.Mz():3===a&&this.j.Gv()))};
g.k.GZ=function(a){if(a){for(a=0;a<this.stills.length;a++)this.F.Ua(this.stills[a].element,!0);this.SI(1)}else this.C=null,this.D=!1;this.Ep()};
g.k.Nf=function(){return this.vb&&Q5(this)};g.v(S5,I5);S5.prototype.show=function(){if(3!==this.player.getPlayerState()){I5.prototype.show.call(this);var a=this.u;if(a){var b=0<this.j.suggestionData.length;g.Co(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.XQ(this.player))||c.GD(!0);this.player.Ua(this.element,!0);this.watchButton.kc(!0)}};
S5.prototype.hide=function(){I5.prototype.hide.call(this);var a;null==(a=g.XQ(this.player))||a.GD(!1);this.player.Ua(this.element,!1);this.watchButton.kc(!1)};g.v(dgb,g.hS);g.k=dgb.prototype;g.k.Yv=function(){var a;if((this.player.V().K("shorts_mode_to_player_api")?this.player.Sb():null==(a=g.XQ(this.player))?0:a.Sb())||this.u)return!0;a=this.player.getVideoData();var b;var c=!!((null==a?0:g.yK(a))||(null==a?0:null==(b=a.suggestions)?0:b.length));b=!agb(this.player)||c;c=a.ij||g.xI(a.B);var d=this.player.uB();a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.k.Nf=function(){return this.endScreen.Nf()};
g.k.g4=function(){return this.Nf()?this.endScreen.EU():!1};
g.k.ra=function(){this.player.Gf("endscreen");g.hS.prototype.ra.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.wb().Ze.get("heartbeat"),d=g.yK(a);!d||b.videoId!==d.videoId||a.aX?(this.player.Hn(b.videoId,void 0,void 0,!0,!0,b),c&&c.rG("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.hS.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.hS.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Yv()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){cgb(this);this.C&&bgb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new K5(this.player):this.endScreen=new P5(this.player),g.D(this,this.endScreen),g.oR(this.player,this.endScreen.element,4))};g.gS("endscreen",dgb);})(_yt_player);
